### ISSUE TITLE
Initial width calculations incorrect?

### ISSUE THREAD

**Issue by mix3d** [highcharts/highcharts-vue#1]
I don't know what the correct way to reproduce this in a shareable way yet, but I was having a strange problem where all the charts are drawn beyond the width of their parent containers. Resizing the page causes them to snap back to the correct size. 

Unfortunate, since it implemented super easily. 

What more can I provide to help dig into the issue?

**Comment by Denyllon** [comment]
Thank you for your report.
Is it occurs also in VanillaJS Highcharts, or just while using this wrapper? Could you try to check it and let us know about the result?

**Comment by dolphinfine** [comment]
I also met this problem,this is sample
https://codesandbox.io/s/w6w74n9vwk

**Comment by mix3d** [comment]
@dolphinfine 's example is a perfect representation of the problem I was seeing.

**Comment by Denyllon** [comment]
Hi @dolphinfine ,

Thank you for the example.
However it looks like the `iview` sets the margin of its `Col` elements too late. The process of rendering looks like that:

1. Columns (without setting margins),
2. Charts (chart container width is set now)
3. Margins (setting `:gutter="8"`)

And that's the reason of why the chart width is not adjusted. To avoid this effect you can apply a little workaround by calling `Chart.reflow()` on `chart.events.load`. Here is the code:

```js
chart: {
    type: "spline",
    events: {
       load() {
           setTimeout(this.reflow.bind(this)); 
       }
    }
},
```

Here is the example: https://codesandbox.io/s/lywp94585m

**Comment by dolphinfine** [comment]
@Denyllon thank you very much,but there are still some problems
https://codesandbox.io/s/p7jjz214xx

**Comment by mix3d** [comment]
@dolphinfine that might be more iView and gutter specific; if you take out the gutter part from the row, the chart width calculates correctly.

**Comment by Denyllon** [comment]
hi @dolphinfine ,

Most likely the problem is related with native Highcharts, not the wrapper. Here is related topic: https://github.com/highcharts/highcharts/issues/6338

Best regards!

**Comment by dolphinfine** [comment]
@Denyllon 
Thank you for your patience. You have helped me a lot.
