### ISSUE TITLE
Cannot set property 'top' of undefined  in  stock.src.js:6810

### ISSUE THREAD

**Issue by pashtetbezd** [highcharts/highcharts-vue#10]
Im using nuxt with latest highchart lib

I setup highcharts-vue as nuxt plugin

```
import Vue from 'vue'
import HighchartsVue from 'highcharts-vue'

Vue.use(HighchartsVue)
```

there is my options 

```
        testOptions: {
          rangeSelector: {
            selected: 1
          },
          title: {
            text: 'AAPL Stock Price'
          },
          series: [{
            name: 'AAPL',
            data: [10, 20, 10, 23, 65, 121, 44, 66, 98, 30, 32, 56, 25, 12, 53],
            pointStart: Date.UTC(2018, 1, 1),
            pointInterval: 1000 * 3600 * 24,
            tooltip: {
              valueDecimals: 2
            }
          }]
        },
```

im trying to init in mounted callback
```
mounted () {
      StockInit(Highcharts)
}
```

on mounted i catched this error

**Comment by Denyllon** [comment]
hi @pashtetbezd ,

`on mounted i catched this error`
Could you tell me, what error you received?
Are you sure that you have imported Stock module?

I suspect that, if you will provide me with mentioned error message, solution will be much easier to find.

Best regards!

**Comment by pashtetbezd** [comment]
There is same error on master branch on highcharts

**Comment by Denyllon** [comment]
Here is what you need to do to avoid the problem:
You can set updateArgs of stock chart to `[true, false]`.

`<highcharts class="stock" :constructor-type="'stockChart'" :options="stockOptions" :updateArgs="[true, false]"></highcharts>`

This problem is related with https://github.com/highcharts/highcharts/issues/8196
