### ISSUE TITLE
How to show Chart loading

### ISSUE THREAD

**Issue by cyberfly** [highcharts/highcharts-vue#100]
Hi i'm using Axios to fetch series data. It will take a couple of seconds to fetch the data. 

How can I show loading indicator before Axios finishing the request using HighChart Vue?

Saw Jquery example on the web but not sure how to implement it using HighChart Vue.

Thanks

**Comment by Denyllon** [comment]
Hi @cyberfly 

Thank you for asking question.
The easiest way to show "Loading..." indicator before axios return the data is by setting it on the chart init, namely using `chart.events.load` and calling `Chart.showLoading()` within function handler. I've prepared the demo with Vue highcharts wrapper, where imitate the axios request, so please take a look on it.

Live example: https://codesandbox.io/s/highcharts-vue-demo-xcp0g
API Reference: https://api.highcharts.com/highcharts/chart.events.load

Kind regards!

**Comment by cyberfly** [comment]
Thanks @Denyllon you are a live saver :)

**Comment by alecellis1985** [comment]
If u have too many data to render this makes no sense at all as it will take more than 2 seconds to render.
