### ISSUE TITLE
【highmaps】labels render wrong

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts-vue#102]
> when i change the wrapper size,the map labels render wrong：

![QQ截图20190809143520](https://user-images.githubusercontent.com/6789138/62759100-f04c7b80-bab2-11e9-841b-d02e6a61f2ac.png)

```javascript
chartOptions.chart.width = chartsW;
chartOptions.chart.height = chartH;
```
```javascript
<highcharts class="highcharts-chart"
                 v-if="chartOptions.colorAxis&&isAggdataFinish"
                 :constructor-type="'mapChart'"
                 :options="chartOptions"
                 :updateArgs="updateArgs"
                 ref="ref-highcharts"></highcharts>
```

**Comment by Denyllon** [comment]
Hello @wjhcc2018 ,

Thank you for reporting the issue.
Could you provide me with minimal example, where the problem occurs?

Kind regards!
