### ISSUE TITLE
Typescript error can't resolve 'highcharts'

### ISSUE THREAD

**Issue by markcouvaras** [highcharts/highcharts-vue#108]
Hi Guys,

I am trying to use Highcharts-Vue with typescript but I am getting the below error:

`ERROR in ./node_modules/highcharts-vue/dist/highcharts-vue.min.js
Module not found: Error: Can't resolve 'highcharts'`

I am currently using the latest version of 1.3.5. Is there another configuration that I should be using as I am under the impression that @types/highcharts should not be installed.

Your help is much appreciated

**Comment by markcouvaras** [comment]
Nevermind, the issue was being caused by the fact that highcharts-vue does not install the correct highcharts library. I had to run 'npm install highcharts' again afterwards to get the latest version

**Comment by 34r7h** [comment]
This wasn't fixed

**Comment by cyborg999** [comment]
holy sh*t. i've been trying to figure out what causes the error. I thought it was  the @types/highcharts. Thanks mah saviour

**Comment by xetryDcoder** [comment]
The problem with my setup was using --save. i installed it without it now it works fine!
