### ISSUE TITLE
highcharts-vue mobile legends error

### ISSUE THREAD

**Issue by kzthet194** [highcharts/highcharts-vue#113]
Hi Team,

We set scrollable chart and move Legend to bottom from right side on mobile. When we update the series data on mobile Legend Data Render is different from preload state and updated series.
In the pre-load state, legend-html is render in 'highcharts-fixed' div.
When we update the series, the legend-html is render in 'highcharts-scrolling' div and there is no legend-html data in 'highcharts-fixed' div.

Do you have any suggestion for this issue?
Thank you!

**Comment by Denyllon** [comment]
Hi @kzthet194 ,

Could you provide me with some minimal example where the issue is noticeable? It would be much easier to solve it and find the source of the problem. You can use any of most common sandboxes like [Codesandbox](https://codesandbox.io/), or [Stackblitz](https://stackblitz.com/).

Kind regards!

**Comment by kzthet194** [comment]
Hi @Denyllon ,

Thanks for your reply. According to your request, I put my example codes from Codesandbox (https://codesandbox.io/s/codesandbox-nuxt-797nm). From there, I created charts.vue under pages.
What my requirement Sanrio is, want to highlight some area as the default with `plotBands` and after user update data from the dropdown which located above of the chart, want to update plotBands area depend on the data what user changed from the dropdown. Actually, that one is not my issue, it's working well with my codes. the issue that I facing is I can't detect the 'highchart-legent' div's data. From the first load, '.highcharts-legend' is located under '.highcharts-fixed' as my following screenshot.
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/56824631/67602652-1b369980-f79d-11e9-9297-be23e05ef848.png">
After the update the select and redraw the graph for update plotBands, that '.highcharts-legend' is moved under '.highcharts-scrolling'
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56824631/67602790-6e105100-f79d-11e9-81d1-93f7912bb4f4.png">
The reason why I want to track '.highcharts-legend' is coz of my styling purpose. Can you help me with this? 
Thanks in Advance!!

**Comment by Denyllon** [comment]
Thank you for sending additional info.
Unfortunately the link from your last comment does not refer the example where the described problem would be noticeable. There is no any chart rendered on the page, so could you take a look on it once again, and provide me with working one?
