### ISSUE TITLE
[Question] Show dynamic series with axios

### ISSUE THREAD

**Issue by gettherefast** [highcharts/highcharts-vue#116]
Hello, I tried to make charts with varying dataset.
I have 8 data.
Data[0] is fetched from api.
while other 7 are static data.

How to make it dynamically render?
How can I wait Data[0] first and then show the chart?
currently I set time out to wait for promise to resolve, sometime it failed, as server are not fast enough, and promise are not resolved yet. it returns with blank data.

How can i make dynamic parameter works and re render the whole chart?, like I will give input range 2-7, so the data will be shown from number 2 to 7 only.
Currently displays all the data.

Here's my codepen => https://codesandbox.io/s/highcharts-vue-demo-bgef2

Thanks

**Comment by Denyllon** [comment]
Hi @gettherefast ,

Thank you for asking question.
I'm wondering why you would not do all actions within `.then()` called after axios get request. Is there any concrete reason why?

I've rebuilt your example a bit, where moved the data assign into the mentioned callback. It will get the data from server, and only then the chart will be filled with dynamic and static data.
I also recommend you to consider showing a static data first, and when the dynamic data comes in the request, then just put it in the series data. In my opinion it could be the 'right' way out. Take a look on the example:  https://codesandbox.io/s/highcharts-vue-demo-4xq63

Kind regards!
