### ISSUE TITLE
Cannot make windbarb working

### ISSUE THREAD

**Issue by RemiDesgrange** [highcharts/highcharts-vue#119]
I have a nuxt js project working fine with highcharts. I wanted to use "windbarb" series type, so I did as follow, in `plugins/highcharts.js`

```js
import Vue from 'vue'
import Highcharts from 'highcharts'
mport HighchartsVue from 'highcharts-vue'
import exportingInit from 'highcharts/modules/exporting'
import windbarbInit from 'highcharts/modules/windbarb'

if (typeof Highcharts === 'object') {
   exportingInit(Highcharts)
   windbarbInit(Highcharts)
}

Vue.use(HighchartsVue)
```

It makes my app crashing in the browser (in nuxt.js I disabled ssr rendering). Any idea how I can make it work ? thanks.

**Comment by Denyllon** [comment]
Thank you for reporting the issue.
I'm not able to reproduce the issue, and definitely need more information, or even minimal demo where the problem occurs. As you can see on the example below, everything works fine.

Live example: https://codesandbox.io/s/highcharts-vue-demo-ovesz

**Comment by RemiDesgrange** [comment]
Ok closing. Sorry for the inconvenience, my data was badly formated, in table I pass to series data there was a timestamp specified, I think windbarb plugin didn't like it.
