### ISSUE TITLE
enableMouseWheelZoom should zoom data only from one side, not from both side

### ISSUE THREAD

**Issue by gautammedhi** [highcharts/highcharts-vue#120]
I have a chart where I use mapNavigation to enableMouseWheelZoom. It's working fine, but while mouse wheel up the data should go to left side, and on mouse wheel down it should again come from one side only. Now the x axis labels are changing from both side. To do anyhting on mouseWheel action, how to implement a function? something like Highcharts.prototype.callbacks and addEvent mousewheel?

**Comment by Denyllon** [comment]
Hi @gautammedhi ,

Thank you for contacting us.
Could you explain the issue more precisely? It would be better to try to produce the demo, where the problem is noticeable, and steps to reproduce as well, so could you provide me with all those things?

Kind regards!
