### ISSUE TITLE
[QUESTION] How can I customize the styles

### ISSUE THREAD

**Issue by aislanmaia** [highcharts/highcharts-vue#124]

**Comment by Denyllon** [comment]
Thank you for asking question.
Could you explain more precisely what would you like to achieve? Which styles do you want to change?

**Comment by aislanmaia** [comment]
I would like something like this:

![image](https://user-images.githubusercontent.com/2199137/70184827-68c0f300-16c7-11ea-80d2-07a065d14770.png)

**Comment by Denyllon** [comment]
This question is definitely related with native Highcharts directly, and would be better to ask about it on support@highcharts.com. This package only wraps the Highcharts library, and here, we're resolving issues for that wrapper only.
