### ISSUE TITLE
Multi interval chart not rendering the line series correctly

### ISSUE THREAD

**Issue by James-Goodbourn** [highcharts/highcharts-vue#126]
Hello.

When creating a chart which has a multi interval series, the series sometimes doesnt render correctly and this varies by chart size.
Here is a screen of the usual chart size we display, with a mixed interval:

![screen 1](https://user-images.githubusercontent.com/8777647/70794209-fcb05000-1d94-11ea-8136-2df9df762ef2.PNG)

The series is there as the tooltip appears when hovering over the series, just no line:

![screen 3](https://user-images.githubusercontent.com/8777647/70794248-21a4c300-1d95-11ea-89a1-a72d25a9060d.PNG)

This happpens at the point the interval changes from 15 minute to 1 hour
Now if we take the same data and apply it to a chart that has a reduced size:

![screen 2](https://user-images.githubusercontent.com/8777647/70794683-20c06100-1d96-11ea-94c1-66dc2763193b.PNG)

The series is drawn correctly.

Thanks

**Comment by sebastianbochan** [comment]
Hi @James-Goodbourn,
Thank you for reporting about the bug. The github is our bugtracker so for general [support](http://www.highcharts.com/support) questions please use forum / stackoverflow or email.

ps. Please try to change the [cropThreshold](https://api.highcharts.com/highcharts/series.line.cropThreshold) and the [threshold](https://api.highcharts.com/highcharts/series.line.threshold) params.

**Comment by James-Goodbourn** [comment]
Hi, 

Changing the settings you mentioned did nothing.

I'm Pretty sure this is a bug, it's the same data being inserted into the charts, the only difference being the size of the chart. 
Why would this produce different results? 
More so why would it make the series invisible when the interval changes, but still display when hovered over?
![screen 3](https://user-images.githubusercontent.com/8777647/70898158-0a134780-1fec-11ea-8e3c-26b64845618a.PNG)

Regards

**Comment by Denyllon** [comment]
Hi @James-Goodbourn 

Could you try to reproduce it in any minimized demo with sample data? It would be great to investigate it on real example.

Kind regards!
