### ISSUE TITLE
heatmap render wrong when i update width and height

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts-vue#129]
![QQ图片20200103102435](https://user-images.githubusercontent.com/6789138/71704104-44b21800-2e13-11ea-9c85-db0761f86c1d.png)
**when i change the charts width and height ,the charts render like this;**
```js
this.$set(chart, 'width', chartsW);
this.$set(chart, 'height', chartH);
```

**Comment by Denyllon** [comment]
Hi @wjhcc2018 ,

Thank you for reporting the issue.
Unfortunately I'm not able to reproduce it using built-in `chart.setSize()` method. Here is the example: https://codesandbox.io/s/highcharts-vue-demo-ylels

Could you provide me with minified demo, where the problem is noticeable?

Kind regards!
