### ISSUE TITLE
How can I make Highcharts auto resize to fit available space?

### ISSUE THREAD

**Issue by SamuelEarl** [highcharts/highcharts-vue#13]
My app has an off canvas menu. When I open and close the menu I would like for my stock chart to automatically resize to fit the available space. I have not been able to get anything to work and am wondering if maybe chart.reflow() would work. I am not sure how to use it within Vue, though, or if the highcharts-vue wrapper even allows us to use chart.reflow(). The first example from [reflow API](https://api.highcharts.com/class-reference/Highcharts.Chart.html#reflow) is exactly what I am looking for.

Please let me know if there is some way that I can get the stock chart to auto resize to fit the available space in my scenario.

Thank you!

**Comment by Denyllon** [comment]
hi @SamuelEarl ,

We are using GitHub as our bugtracker, so if you have questions, please contact our support: https://www.highcharts.com/support. I recommend you to post your question on this forum:
https://forum.highcharts.com/

Best regards!
