### ISSUE TITLE
Access to 'highcharts-more' Chart types

### ISSUE THREAD

**Issue by kramey56** [highcharts/highcharts-vue#131]
I was experimenting with different types of charts and happened to try the "Gauge" type chart. On load, the browser complained that I did not have the "highcharts-more" module loaded. Is this available from highcharts-vue? If so; how do I enable it? If not; are there any plans to add this support?

Thanks.

Ken Ramey

**Comment by Denyllon** [comment]
Hi @kramey56 ,

Thank you for contacting us.
This package is only a wrapper for Highcharts library, what means that it is required to install Highcharts before using it.

If you would like to load a module, you can read more about that in [Importing Highcharts Modules](https://github.com/highcharts/highcharts-vue#importing-highcharts-modules) section of wrapper documentation.

Here is the example which show how to load the `highcharts-more` module and `arearange` series type: https://codesandbox.io/s/highcharts-vue-demo-xhkif 

Kind regards!
