### ISSUE TITLE
Highcharts error #17 - Missing Module for Treemap

### ISSUE THREAD

**Issue by sharden** [highcharts/highcharts-vue#132]
Encountering an issue were the Treemap module is not being recognized by the highcharts-vue wrapper. Is anyone else seeing this issue? 

**Error link reference:** https://www.highcharts.com/errors/17/?missingModuleFor=treemap 

Here is a **similar issue with another module that was closed:** https://github.com/highcharts/highcharts-vue/issues/59 

**Other notes:**
- I have a pie chart and bar chart working with no issues so Highcharts and HighchartsVue is initialized properly.
- The treemap module does exist in my node modules folder.

**Comment by Denyllon** [comment]
Hi @sharden ,
Thank you for your report. Are you sure that you loaded the **treemap** module in the way described in docs? Here you can find the instruction: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

Kind regards!

**Comment by sharden** [comment]
@Denyllon Thanks for having me take a second look at the docs. I forgot to **"add the by passing highcharts to it"** after I imported it. 

Here is an example of my main.js file for anyone else who came across this error (because I couldn't find one)

import App from './App.vue'
import Vue from 'vue'
import Highcharts from 'highcharts'
import Treemap from 'highcharts/modules/treemap'
import HighchartsVue from 'highcharts-vue'


Vue.use(Highcharts, Treemap, HighchartsVue)

Vue.config.productionTip = false

// add the module by passing highcharts to it
Treemap(Highcharts)

new Vue({
  render: h => h(App),
}).$mount('#app')
