### ISSUE TITLE
Formatter vue component

### ISSUE THREAD

**Issue by whoisme555** [highcharts/highcharts-vue#136]
In the tooltip formatter, is there a way to use a vue component rather than just using html strings?

We've got a fairly complex custom formatter, and I'd love to remove all the jquery dependencies by using a vue component instead.

Is there any information on either using a vue component in the string itself or a slot?

**Comment by Denyllon** [comment]
Hi @whoisme555 

Thank you for contacting us.
It is not possible to neither return the VNode, nor HTML element from formatter function. However, you can use a common plugin for Vue v2+, which is actually an equivalent of React Portals, and it's called [vue-portal](https://portal-vue.linusb.org/), combined with JSX syntax. Then it will be possible to define your own "view" for tooltip, and just put into into its HTML element.

Note: This solution is a bit complex, and requires calling chart core functions, so if something will not be clear enough, feel free to ask about that.

Live example: https://codesandbox.io/s/highcharts-vue-demo-voo9m

Kind regards!

**Comment by EdmundoDelGusto** [comment]
Is it possible you could rewrite this using options-api?
I tried to do this for hours now and can't get it working.

**Comment by EdmundoDelGusto** [comment]
Hi, @Denyllon. Thank you for your code.

I was struggeling on this for three days now.
I cannot use JSX in my project for now.

For everyone else out there, I created an example without using JSX

https://stackoverflow.com/questions/77106264/displaying-a-vue-component-inside-highcharts-tooltip-via-vue-portal
