### ISSUE TITLE
Tooltip cannot be displayed

### ISSUE THREAD

**Issue by wangyouping** [highcharts/highcharts-vue#139]
I found that on some mobile browsers, if the chart is not on the first screen of the screen, the tooltip cannot be displayed by clicking outside the broken line.

**Comment by wangyouping** [comment]
I found that on some mobile browsers (for example, WeChat browser), if the chart is not on the first screen of the screen,  the tooltip cannot display when clicking the area outside the line

**Comment by Denyllon** [comment]
Thank you for reporting the issue.

Could you provide me with some live example, where the problem is noticeable? You can start reproducing process from here: https://codesandbox.io/s/highcharts-vue-demo-n7usd

Kind regards!

**Comment by wangyouping** [comment]
Thank you for your reply.
We researched it and found that it conflicted with some components in the project.

**Comment by wangyouping** [comment]
> Thank you for reporting the issue.
> 
> Could you provide me with some live example, where the problem is noticeable? You can start reproducing process from here: https://codesandbox.io/s/highcharts-vue-demo-n7usd
> 
> Kind regards!

Thank you for your reply.
We researched it and found that it conflicted with some components in the project.
