### ISSUE TITLE
When I open the options3d of the column, it will report this error, only the column

### ISSUE THREAD

**Issue by jiazhuangzhexiaozhang** [highcharts/highcharts-vue#142]
![微信图片_20200601105557](https://user-images.githubusercontent.com/31621564/83392294-6eee1d00-a427-11ea-8b6e-b781a6d38983.jpg)

**Comment by Denyllon** [comment]
Hi @jiazhuangzhexiaozhang 

Thank you for contacting us. Could you provide me with more detailed description of what is happening and when, as well as the demo where I would be able to notice the issue from the above screenshot?

Kind regards!

**Comment by jiazhuangzhexiaozhang** [comment]
> 嗨@jiazhuangzhexiaozhang
> 
> 感谢您与我们联系。您能否为我提供有关发生的情况和时间的详细说明，以及可以从上面的屏幕截图中注意到该问题的演示？
> 
> 亲切的问候！

**Comment by jiazhuangzhexiaozhang** [comment]
> Hi @jiazhuangzhexiaozhang
> 
> Thank you for contacting us. Could you provide me with more detailed description of what is happening and when, as well as the demo where I would be able to notice the issue from the above screenshot?
> 
> Kind regards!

I found the problem, when options3d is used, the stack attribute in the series cannot be empty
