### ISSUE TITLE
Datagrouping in vue

### ISSUE THREAD

**Issue by taufiknur** [highcharts/highcharts-vue#144]
Hello, how to make datagroup and make loading if user select range data as below.. in html work fine,,how about vue?

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/lazy-loading/

**Comment by Denyllon** [comment]
Hi @taufiknur ,

Thank you for contacting us.
I reproduced mentioned demo using this wrapper, so please take a look on it. Looks that is working well.
https://codesandbox.io/s/highcharts-vue-demo-j7d5p

Kind regards!

**Comment by taufiknur** [comment]
thank, you are saving my time
