### ISSUE TITLE
Error rendering empty pie charts with Highcharts 8.1.1

### ISSUE THREAD

**Issue by pablolmedorado** [highcharts/highcharts-vue#147]
I've noticed that **after upgrading to Highcharts 8.1.1**, empty pie charts stopped working.

I'm getting the following error:
`[Vue warn]: Error in mounted hook: "ReferenceError: Highcharts is not defined"`

Using 8.1.0 everything works as expected.

Thanks in advance.

[Live example](https://codesandbox.io/s/highcharts-vue-demo-ye65e)

PS: Sorry if I've made a mistake posting the issue here, but it seems to work fine in the official Highcharts demos.

**Comment by pawelfus** [comment]
Thanks for reporting the issue. It's a bug in Highcharts core: https://github.com/highcharts/highcharts/issues/13681 - this should be already fixed and v8.1.2 will be released soon.
