### ISSUE TITLE
Contour charts implementation

### ISSUE THREAD

**Issue by manisha-500** [highcharts/highcharts-vue#149]
Does highcharts-vue support contour charts implementation? If yes, can you please provide solution/reference on how to implement. Here is the ref : [http://jsfiddle.net/3bq0qqzb/2/](http://jsfiddle.net/3bq0qqzb/2/)

**Comment by Denyllon** [comment]
Hi @manisha-500,

Thanks for asking question.
I reproduced the attached example specially for you. Here is it: https://codesandbox.io/s/highcharts-vue-demo-jdqyo

Kind regards!
