### ISSUE TITLE
How to acces to Highcharts method after rendering ?

### ISSUE THREAD

**Issue by Taxman972** [highcharts/highcharts-vue#15]
I already use this configuration to set global options to Highcharts:

<pre>
import Highcharts from 'highcharts';
Highcharts.setOptions({
    lang: {
        decimalPoint: '.',
        drillUpText: '<<',
        noData: '...',
        resetZoom: 'R.Z.',
        thousandsSep: ' '
    }
});
</pre>

Now how can I access to Highcharts after rendering the charts like the [numberFormat](https://api.highcharts.com/class-reference/Highcharts#numberFormat) method in tooltips ?

**chart.vue**
<pre>
...
tooltip:{
        formatter: function(){
        return this.key //+ ' : ' + Highcharts.numberFormat(this.y,2);
    }
},
...
</pre>

[Link](https://codesandbox.io/s/k91o16xr7)

**Comment by Denyllon** [comment]
hi @Taxman972 ,

You need to `import` Highcharts inside the **Chart.vue**  file. Then you will be able to use built-in methods in your component. 

```js
import Highcharts from 'highcharts'

export default {
  data() {
    return {}
  }
}
```

Best regards!
