### ISSUE TITLE
Pie chart with all zeros as series data - Highcharts is not defined

### ISSUE THREAD

**Issue by jgraham44** [highcharts/highcharts-vue#150]
Since the update of highcharts from 8.1.0 to 8.1.*, I receive a highcharts is not defined error when rendering a pie with data of all zeros (waiting for data from an api call). 

I have reproduced this [here ](https://codesandbox.io/s/highcharts-vue-demo-exz78).

If you change the dependency to 8.1.0 it will render an empty pie; however with 8.1.2 you can see the errors in the console. 

So far, the pie is the only one I have seen with this functionality break.

**Comment by pawelfus** [comment]
Thanks for reporting the issue @jgraham44 

It's a bug in the core, take a look: https://github.com/highcharts/highcharts/issues/13710

Closing as a duplicate.

**Comment by jgraham44** [comment]
Thanks for the information! Sorry for the false alarm.
