### ISSUE TITLE
Options in charts computed 

### ISSUE THREAD

**Issue by ingYanetEnnis** [highcharts/highcharts-vue#152]
In the chart component I see the changes but the graphics are not always updated. Should I do something special to let you know there was a change? or should it work?
```

<template>
  <div class="graph-main">
    <chart
      ref="highcharts"
      :options="options"
    />
  </div>
</template>

<script>
import Vue from 'vue';
import Highcharts from "highcharts";
import exportingInit from 'highcharts/modules/exporting';
import addVariablePie from 'highcharts/modules/variable-pie';
import addMore from 'highcharts/highcharts-more';
import stockInit from "highcharts/modules/stock";
import {Chart} from 'highcharts-vue'
stockInit(Highcharts);
addVariablePie(Highcharts);
addMore(Highcharts);
exportingInit(Highcharts);

export default {
  props: {
    chart: {
      default: null,
      type: Object
    },

  },
  components: {Chart},
  data() {
    return {
      polar: false,
      chartTypes : {
        line: 'line', stacked_bar: 'bar', stacked_area: 'area',
        semi_pie: 'pie', variablepie: 'variablepie', polar: 'polar' }
    };
  },
  computed: {
     options: function () {
           ...logic
      let options = {
          .....logic
         chart: {
          type: this.chartType,
          polar: this.chartType == "polar" ? true : false,
          plotBackgroundColor: '#EEEEEE',
        },
          series : this.series
      }
      return options;
    },
    chartType(){
      return this.chartTypes[this.chart.chartType] ? this.chartTypes[this.chart.chartType] : "column";
    },

    series: function (){
      logic according to type of graph
      return series;
    },
    }
  },
```

Example not update graphic  

<img width="551" alt="Screen Shot 2020-06-25 at 10 37 04" src="https://user-images.githubusercontent.com/25614472/85730202-d9fddd00-b6cf-11ea-8fd9-decb2c52df5d.png">

<img width="565" alt="Screen Shot 2020-06-25 at 10 35 54" src="https://user-images.githubusercontent.com/25614472/85730034-b33fa680-b6cf-11ea-8aad-e9ee1147c050.png">

**Comment by mrkalmdn** [comment]
Hey @ingYanetEnnis! Seems like you have found a solution for dynamically updating the `chartOptions`. What's your workaround with this? Thanks!

**Comment by Denyllon** [comment]
Hi @mrkalmdn ,

All chart options which are put into the component's data (or computed data), suppose to be dynamic, and this wrapper should react when thy are changing. Could you be more precise about what problem have you encountered? I think that we could help you to resolve it, after getting more details.

Kind regards!
