### ISSUE TITLE
Legend Texts Garbled / Overlaps

### ISSUE THREAD

**Issue by matthewsuan** [highcharts/highcharts-vue#155]
When updating series on pie chart with variable number of items, the legend gets garbled. 

It seems it is retaining the previous legend rendered elements.

https://www.dropbox.com/s/99ez6rxyipjosly/Screenshot%202020-07-08%2018.23.39.png?dl=0

**Comment by Denyllon** [comment]
Hi @matthewsuan ,

Could you provide me with the minimal example, where the problem is noticeable?

Kind regards!
