### ISSUE TITLE
Network graph does not work using the demo options (throws "cannot read property removeElementFromCollection of undefined")

### ISSUE THREAD

**Issue by SnirShechter** [highcharts/highcharts-vue#158]
I admit I haven't gone deeper into the library to figure out what's wrong, but it seems like it's related to the Vue integration, since using the vanilla highcharts library works just fine.

### Reproduction
* Copy the options from the demo: https://www.highcharts.com/demo/network-graph
* Apply to a Highcharts component
* Error:
![image](https://user-images.githubusercontent.com/26040325/89125590-3a124b00-d4e8-11ea-9ada-55013b9e4c13.png)

### Libraries
* highcharts: 8.1.2
* highcharts-vue: 1.3.5

**Comment by pawelfus** [comment]
Thanks for reporting! Looks like a duplicate of https://github.com/highcharts/highcharts/issues/13570 - could you test the workaround and let us know the results? Thanks!

**Comment by Denyllon** [comment]
Hi @SnirShechter,

I've just copied the configuration from the mentioned demo, and there is no any error thrown in the console: https://codesandbox.io/s/highcharts-vue-demo-dv6vn
Could you provide us with the example where the problem is noticeable?

Kind regards!

**Comment by SnirShechter** [comment]
Seems to be working just fine in codesandbox. I'll close this and reopen if I encounter these errors again.

Thanks!
