### ISSUE TITLE
is it possible to create Stock chart with custom GUI?

### ISSUE THREAD

**Issue by hemanth-sp** [highcharts/highcharts-vue#163]
two-pane stock chart is possible to make using highcharts-vue? 
![Screenshot from 2020-10-20 16-04-00](https://user-images.githubusercontent.com/24698571/96575195-147a2e00-12ee-11eb-8ad5-89c030d8220a.png)
when click on custom gui effect not working

**Comment by Denyllon** [comment]
Hi @hemanth-sp ,

Thanks for opening the another issue.
Did you get rid of your problems, or need some help from us?

Kind regards!

**Comment by hemanth-sp** [comment]
Yes I can easily implemented the stock with custom gui
