### ISSUE TITLE
Need to connect Json objects via props 

### ISSUE THREAD

**Issue by sureshwisdom** [highcharts/highcharts-vue#167]
I am having JSON object data which needs to place high chart series.

**Comment by Denyllon** [comment]
Hello @sureshwisdom ,

Appreciate you contacting us.
Could you try to describe in more detail what issue did you encounter? Unfortunately I'm not quite sure what the problem is, and what do you want to achieve.

Kind regards!

**Comment by k-sai-kiranmayee** [comment]
Hello!
I'm using Vue 2.x, for chartOptions I'm setting the data object which is obtained through a prop (which is of object type obtained from JSON), now before setting that I want to add `formatter` for the labels of the xAxis, I'm unable to get the reference of `this.value`

Have imported highcharts too

So this is how I want to set
```
chartOptions() {
      const chartData = this.chart; // chart is the prop in this component
      chartData.xAxis = {
        labels: {
          formatter() {
            return Highcharts.dateFormat('%d/%b/%Y', this.value); // I'm unable to get **this.value**
          },
        },
      };
      return {
        chartData,
      };
    },
```
Could anyone help, please

**Comment by Denyllon** [comment]
Closed due to inactivity.
