### ISSUE TITLE
how to enable stock tools

### ISSUE THREAD

**Issue by nicqchen** [highcharts/highcharts-vue#168]
could you share some examples about how to ennable the stock stools?

**Comment by nicqchen** [comment]
anyone could help on this topic?

**Comment by Denyllon** [comment]
Hi @nicqchen ,

Thank you for asking question.
Here is the demo which shows how to configure stock tools with Highcharts Vue wrapper: wrapper.https://codesandbox.io/s/highcharts-vue-demo-forked-pebej

Hope it will help you to achieve what you need.

Kind regards!
