### ISSUE TITLE
Install plugins

### ISSUE THREAD

**Issue by AdamBolfik** [highcharts/highcharts-vue#171]
I am trying to install a few plugins, one being the [highcharts-regression](https://github.com/streamlinesocial/highcharts-regression) plugin, and am unable to find any documentation/examples from anywhere other than installing highchart modules. 

I tried importing highcharts in my component and manually calling the plugin install, but the component does not appear to use that highcharts instance(?)...

For example:
```javascript
...
import * as Highcharts from 'highcharts'
import regression from 'highcharts-regression';
import {Chart} from 'highcharts-vue';

regression(Highcharts);
...
```

Any help would be very appreciated.

**Comment by Denyllon** [comment]
Hi @AdamBolfik ,

Sorry for a bit of delay in replying in this thread.
As I see, the `highcharts-regression` plugin works fine with Highcharts Vue wrapper to me, and did not noticed any problems while implementing basic demo. Here is it: https://codesandbox.io/s/highcharts-vue-demo-forked-vfwcg

Regarding installing modules, you just to import them as it is described on this wrapper's documentation: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

If you also wanted to use a specific Highcharts instance, of course you can pass it through component's props. Here is a detailed description: https://github.com/highcharts/highcharts-vue#using-a-specific-highcharts-instance

Hope it will help you to dispel your doubts, but if not, then feel free to contact our support team (through the one of available [support channels](https://www.highcharts.com/blog/support/)) to get more 
Kind regards!
