### ISSUE TITLE
how do i show only some x axis values? 

### ISSUE THREAD

**Issue by bootsmann95** [highcharts/highcharts-vue#176]
Hello I have a chart looking like this:

![image](https://user-images.githubusercontent.com/53180316/105043308-ad435580-5a65-11eb-96ec-76d8d149f76e.png)

I have way too many xAxis values, how do i only show like 10 values based on  fx. 10 average?

**Comment by Denyllon** [comment]
Hi @bootsmann95 ,

Thank you for contacting us.
It is a typical Highcharts support question, so in the future, when having a similar doubts about the usage, would be always better to dispel them through asking on one of official support channels like Forum, StackOverflow, Skype (for clients with Advantage subscription), or directly via email support@highcharts.com

Anyway, in this case I would suggest to take a look on a bunch of API options, like:
https://api.highcharts.com/highcharts/xAxis.tickAmount - to set fixed ticks number,
https://api.highcharts.com/highcharts/xAxis.tickInterval - to set fixed interval (time in this case) between ticks, or even:
https://api.highcharts.com/highcharts/xAxis.tickPositioner - a function which could manually define the way of how ticks are positioned on the axis, in your own custom way.

Kind regards!
