### ISSUE TITLE
SVG to export

### ISSUE THREAD

**Issue by lgmf** [highcharts/highcharts-vue#179]
Hi!

How can I access the "chart" to use the `getSVG`method (https://api.highcharts.com/class-reference/Highcharts.Chart#getSVG)?

**Comment by Denyllon** [comment]
Hi @lgmf 

Thank you for contacting us.
You can access the `chart` reference within `mounted()` lifecycle hook, like here:
https://codesandbox.io/s/highcharts-vue-demo-forked-hb01k?file=/src/components/Chart.vue

Docs: https://github.com/highcharts/highcharts-vue#chart-object-reference

Kind regards!
