### ISSUE TITLE
How includes momentjs?

### ISSUE THREAD

**Issue by kelvym** [highcharts/highcharts-vue#18]
How use **momentjs** next to **highchart-vue**?
Error:
 **Highcharts Error #25
Can't find Moment.js library
Using the global.timezone option requires the Moment.js library to be loaded.**

**Comment by Denyllon** [comment]
I've already answered to your question here: https://stackoverflow.com/questions/51487060/highchart-vue-how-includes-momentjs/51496662?noredirect=1#comment89969601_51496662
