### ISSUE TITLE
Annotation position being reset

### ISSUE THREAD

**Issue by Mimu1988** [highcharts/highcharts-vue#198]
Hello,

Why are my annotation positions reset everytime i add a new annotation (see https://codesandbox.io/s/highcharts-vue-demo-forked-m3trl?file=/src/components/Chart.vue). Add Annotation (Button) --> first annotation will be added --> drag&drop first annotation --> Add Annotation(Button) --> second annotation will be added and position of first annotation will be reset

Got a running java web ee application with the same functionality where the positions of the annotations won´t be reset.

Thanks

**Comment by ajmoralesa** [comment]
@Mimu1988 did you find a better solution to your problem? Thanks
