### ISSUE TITLE
Highstock not rendering correctly

### ISSUE THREAD

**Issue by MirzetKameric** [highcharts/highcharts-vue#20]
I'm trying to add stockChart from your demo app but i get this error.  

stock.js?37d8:105 Uncaught TypeError: Cannot set property 'top' of undefined
    at a.Chart.eval (stock.js?37d8:105)
    at eval (highcharts.js?ea7f:31)
    at Array.forEach (<anonymous>)
    at Object.a.each (highcharts.js?ea7f:28)
    at a.fireEvent (highcharts.js?ea7f:30)
    at a.Chart.setChartSize (highcharts.js?ea7f:261)
    at a.Chart.setSize (highcharts.js?ea7f:258)
    at eval (highcharts.js?ea7f:257)

And this one:
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:588 [Vue warn]: Error in callback for watcher "options": "TypeError: Cannot set property 'top' of undefined"
found in
---> <Highcharts>
       <BurndownChart> at src\components\BurndownChart.vue
         <App> at src\App.vue
           <Root>

I added all this to main.js 
import HighchartsVue from 'highcharts-vue'
import Highcharts from 'highcharts'
import stockInit from 'highcharts/modules/stock'

stockInit(Highcharts)
Vue.use(HighchartsVue)

and have proper values. Tried your example and other data.

**Comment by mrchoke** [comment]
try  :updateArgs="[true,false]" in <highcharts> tag

**Comment by Denyllon** [comment]
Thank you for your report. Actually, it's not the problem with wrapper itself, but native Highcharts, and it's already reported here: https://github.com/highcharts/highcharts/issues/8196 . 

As @mrchoke said, at this moment you can set the `oneToOne` flag equal to false by setting `:updateArgs="[true,false]"` on your Highstock component definition.

Kind regards!

**Comment by MirzetKameric** [comment]
Thank you guys. That fix worked!

**Comment by Denyllon** [comment]
It should be fixed in new upcoming version of Highcharts. Then it shoudn't be necessary to set this options.
