### ISSUE TITLE
Highcharts Vue Ignores Responsive Settings 

### ISSUE THREAD

**Issue by bc-whisnant** [highcharts/highcharts-vue#200]
In Highcharts we can use a responsive array as part of our chart options to control the behavior of the chart under certain conditions (maxWidth, for example.). However, it seems that highcharts vue ignores this in some way. Please see this example for more details: https://codesandbox.io/s/highcharts-vue-demo-forked-7qdlk?file=/src/main.js. I am also including a link to the highcharts api for reference: https://api.highcharts.com/highcharts/responsive.

Thank you.

**Comment by Denyllon** [comment]
Hi @bc-whisnant ,

Thank you for contacting us, and appreciate you're using our product!
Unfortunately, I'm not able to reproduce any issue related to setting responsiveness through `chartOptions`. Here is the demo, which shows that `responsive` works like a charm: https://codesandbox.io/s/highcharts-vue-demo-forked-81b84
(please resize the chart to the smaller width, to see the line color is changing)

By the way, your demo doesn't include any responsive options, so could you provide me with a correct one?

Best regards!

**Comment by jakubSzuminski** [comment]
`responsive` seems to work normally well with **Highcharts-Vue**. If you have config-related issues, you can ask questions on the Highcharts forum: https://www.highcharts.com/forum/
