### ISSUE TITLE
HowTo apply Tree shaking / cherry picking via Vue wrapper?

### ISSUE THREAD

**Issue by gmw-web** [highcharts/highcharts-vue#202]
Hi,

I'm wondering how to apply tree shaking when using the Vue wrapper for Highcharts. I understood from https://github.com/highcharts/highcharts/issues/8667 that the main library needed to be modularized first, but that appears to have been completed. 

If, for example, I wanted to use _only_ a basic line chart, how do I apply tree shaking via the Vue wrapper? Is this possible and/or is there perhaps a demo I can check out?

Thanks in advance!

**Comment by Denyllon** [comment]
Hello @gmw-web ,

Thank you for your question, and apologize you've been waiting for so long.
The Highcharts Vue wrapper does not have its own implementation of enabling / disabling the tree shaking, but (as you mentioned) you can produce your own custom build of Highcharts, which has the line series only, and then use the [Highcharts](https://github.com/highcharts/highcharts-vue#using-a-specific-highcharts-instance) option while registering the plugin. Then you can pass your own Highcharts instance which has been built on your custom preferences.

**Comment by gmw-web** [comment]
Ok, that makes sense. Thanks for the explanation!
