### ISSUE TITLE
keyboard accessibility

### ISSUE THREAD

**Issue by JamieGarcia123** [highcharts/highcharts-vue#203]
do we add keyboardAccessibility under the chartoptions? 

this.summaryChartOptions = {
        accessibility: {
            keyboardNavigation: {
              enabled: true,
              focusBorder: {
                enabled: true,
                hideBrowserFocusOutline: true,
                margin: 2,
                style: {
                  borderRadius: 3,
                  color: "#335cad",
                  lineWidth: 2,
                },
              },
            },
          },
          
          like so? 

added a head tag in the vue file too
  head() {
    return {
      script: {
        src: "https://code.highcharts.com/modules/accessibility.js",
      },
    };
  },
  
  

still cant get keyboards navigation 

adding more to this... head method probably is a nuxt thing not just a vue thing....

MAIN.JS file 
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import AccessibilityOptions from "highcharts";
import VueHighcharts from "vue-highcharts";
import Highcharts from "highcharts/highmaps";
import HighchartsVue from "highcharts-vue";
import accessibility from "highcharts/modules/accessibility";

<script src="https://code.highcharts.com/modules/accessibility.js"></script>;

Vue.config.productionTip = false;
new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount("#app");

Vue.use(VueHighcharts, { Highcharts });

Vue.use(HighchartsVue);

Vue.use(AccessibilityOptions);

Vue.use(accessibility);
Highcharts.setOptions({
  accessibility: {
    keyboardNavigation: {
      enabled: true,
    },
  },
});

```

**Comment by JamieGarcia123** [comment]
closing this --- i just noticed we use vue-highcharts not your highcharts-vue

**Comment by JamieGarcia123** [comment]
i got this resolved.

**Comment by lbineau** [comment]
Could you kindly put your solution in a comment?
