### ISSUE TITLE
ReferenceError with nuxt

### ISSUE THREAD

**Issue by avpuchkova** [highcharts/highcharts-vue#212]
Hello! I use nuxt on project and try to install highcharts-vue. There is such issue:
ReferenceError
window is not defined

node_modules\highcharts-vue\dist\highcharts-vue.min.js

![изображение](https://user-images.githubusercontent.com/80326032/164236549-c06dc8f0-82ed-4d7a-aa6b-46cdd33c8986.png)

**Comment by avpuchkova** [comment]
I resolve it installing chart as **npm i nuxt-highcharts**.

**Comment by RosarioAleCali** [comment]
@avpuchkova I ended up resolving it by importing the [plugin only for the client side](https://nuxt.com/docs/guide/directory-structure/plugins).
