### ISSUE TITLE
Calling chart.destroy causes error

### ISSUE THREAD

**Issue by ldsenow** [highcharts/highcharts-vue#214]
Hi,

it is related to issue https://github.com/highcharts/highcharts/issues/11553 

My comment about the issue, i hope it helps to resolve the error. https://github.com/highcharts/highcharts/issues/11553#issuecomment-1125602415

**Comment by ldsenow** [comment]
Is this repo being maintained? Can I do a PR for this or would someone take a look?

**Comment by jakubSzuminski** [comment]
Closing as it is a duplicate of this issue: https://github.com/highcharts/highcharts-vue/issues/249
