### ISSUE TITLE
HC and vue lifecycle, dynamic options vs updates

### ISSUE THREAD

**Issue by augnustin** [highcharts/highcharts-vue#215]
We are using HC along with Vue2 and highcharts-vue wrapper for quite some time now and it works fairly well.

But when I try to have deeper control over what's happening between vue and HC, I get confused.

For instance, it is reasonable to set options as a `computed` prop or should it always be set as a `data` prop?

It seems to work in most cases with the `computed` prop but for more complex usages, it won't and one has to use an `update` method.

Eg.

```
<template>
  <highcharts :options="options" />
</template>

<script>
export default {
  computed: {
    options() {
       return {
           title: {
            text: this.title, // changes if this.title is updated
          },
          xAxis: {
            crosshair: {
               width: this.crosshairWidth, // doesn't change if this.crosshairWidth is updated
            }
          },
       }
    }
  },
  props: {
    title: { 
      type: String,
    },
    crosshairWidth: {
      type: Number,
    }
  }
}
</script>
```

So for `crosshairWidth` I guess the solution could be to add:

```
watch: {
  crosshairWidth() {
     this.chart.xAxis[0].update({
       crosshair: {
         width: this.crosshairWidth,
       }
     })
  }
}
```
along with `this.chart` ref stored on load.

But the question is, shouldn't this be the job of the wrapper to handle those cases? When can we use dynamic options vs. updates? 

I'm pretty unclear on how vue and highcharts interact.

Hope it is clear and this gets some interest, since I'm aware vue3 is now here and my change the game on this topic.

**Comment by jakubSzuminski** [comment]
Thanks for reporting & apologies for the late response.

That's exactly what's happening: 
https://github.com/highcharts/highcharts-vue/blob/20a6874119e5be68245a488c333c75a64f159a3b/src/component.js#L43-L50

In short: we are watching for any changes in the `chartOptions`. Once there is a change, we always call the `chart.update` method. It does not matter whether `chartOptions` is a `ref` or a `computed` object.

Here's a demo: https://codesandbox.io/s/cool-heyrovsky-r4xwtr?file=/src/App.vue

In case you need any help, please reproduce your issue and I will gladly investigate what's going on and try to propose a solution.
