### ISSUE TITLE
Composition API

### ISSUE THREAD

**Issue by ObjectAssign** [highcharts/highcharts-vue#221]
This does not work well with the new VUE composition API

Also, how do I enable boost mode?

**Comment by ObjectAssign** [comment]
Bump

**Comment by Denyllon** [comment]
Hello @ObjectAssign,

Unfortunately this wrapper does not support the Vue Composition API yet. We've plans to implement some improvements in the near future. Regarding the boost module, it should be able turn on the same way as any other module.

In case of any further questions, feel free to ask them.

API Docs: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

Kind regards!

**Comment by jakubSzuminski** [comment]
Hi @ObjectAssign,

I just wanted to let you know that we've published the latest version of the **highcharts-vue** package which now offers full support for Composition API. 

You can take a look at the demo we've included in the `demo-v3` folder in this repo to see an example of usage.

Do not hesitate to ask in case you have any problems with this.
