### ISSUE TITLE
How to add an image to the legend?

### ISSUE THREAD

**Issue by gbr0105** [highcharts/highcharts-vue#222]
How does highcharts fill the background image into each cell(treemap), based on vue

**Comment by Denyllon** [comment]
Hi @gbr0105 ,

Appreciate your question, and sorry for the delay, but this question looks to me like the typical support question, but here (the issues tab) serves us to track the bugs of this package. You can always ask question choosing the most convenient support channel for you, and contacting Highcharts support team. It's possible to ask the question on our forum, StackOverflow platform, or directly through sending an email.

https://www.highcharts.com/blog/support/

Kind regards!
