### ISSUE TITLE
SSR Friendly

### ISSUE THREAD

**Issue by ObjectAssign** [highcharts/highcharts-vue#224]
Hi this does not work well with Inertia/SSR as it uses the window object.

Would be nice with an overhaul to support SSR + Composition API

**Comment by Denyllon** [comment]
Hello @ObjectAssign 

We're aware that package has some problems with SRR, but as I mentioned in your another issue, we are planning to improve this wrapper for getting better type definitions, composition API, as well as the SRR support. In a meanwhile, you can temporarily try to use the workarounds described [here](https://github.com/highcharts/highcharts-vue/issues/193#issuecomment-939326130).

Kind regards!

**Comment by jakubSzuminski** [comment]
The `highcharts-vue` package works with Nuxt. Similarly to `highcharts-react` with Next (https://github.com/highcharts/highcharts-react#highcharts-with-nextjs), you need to check whether the code is ran on the server or on the client-side.

When it's being executed on the server, you will not be able to access Highcharts as it's a purely client-side library.

If you wish to "export your charts" you can check out our Export Server solution: https://github.com/highcharts/node-export-server which in response to an HTTP request will return an image of a chart created with your chart's config.
