### ISSUE TITLE
Chart object inaccessible since 1.4.1

### ISSUE THREAD

**Issue by 0ip** [highcharts/highcharts-vue#235]
Since 1.4.1, I cannot access the chart object anymore using ref. Before that version, this example used to work:

```
<Chart
    :options="chartOptions"
    ref="chartRef"
></Chart>
...
<script setup>
import { Chart } from 'highcharts-vue'
...
chartRef.chart.zoomOut()
```

**Comment by jakubSzuminski** [comment]
Hi @0ip,

Thanks for reporting!

You're right, the `chartRef` behavior seems to have changed with this update. I'll prioritize this issue and start working on it right away.

I'll keep you posted.

**Comment by jakubSzuminski** [comment]
@0ip,

The fix is now ready on this repo and will be available within the next release (probably next week). 

For now, you can just install the package from our GitHub link by adding this to your `package.json`:
`highcharts-vue: 'https://github.com/highcharts/highcharts-vue/'`

Let me know if everything works now.

**Comment by 0ip** [comment]
Thank you for addressing this issue so quickly.

Accessing the chart object instance does work now, but it appears as if some chart settings e.g. regarding hover states are now modified upon changing chart data or calling chart methods. For example, upon calling `zoomOut()`, hovering over the line graph causes my line chart to be slightly faded out. Also, interaction with the chart appears to be much slower for some reason, compared to 1.4.0.

I'm sorry that the above description is rather vague. It might very well be specific to my setup. I'll get back to you with more concrete info as soon as I have more time.

**Comment by jakubSzuminski** [comment]
No worries, just come back to me when you have more conrete info about your performance issues.

In the meantime I'll try to test the performance myself and see what might go wrong.

I'll let you know here if I find something out. I'll create a new issue for this then.

**Comment by jakubSzuminski** [comment]
@0ip, just wanted to let you know that it has been fixed with the latest release. Here's a simple example: https://codesandbox.io/s/vue-3-composition-api-demo-forked-z0mvhl?file=/src/components/Chart.vue

Feel free to use highcharts-vue@1.4.2 :)

**Comment by 0ip** [comment]
@jakubSzuminski Thanks for letting me know about the release! 👍 

So I think one the issue I was referring to was introduced in 1.4.1, given that this fix is rather timid if I may say so haha

Using your example, when changing the last data point, hovering the line chart shouldn't alter its opacity, but for some reason, it does for me:
<img width="684" alt="image" src="https://github.com/highcharts/highcharts-vue/assets/757230/ecf1a254-885f-4c25-9bbe-00c1a4a23be8">

Unfortunately the app does not let me select version 1.4.1, but if you try 1.4.0, it does work as expected, i.e. nothing is altered design-wise.
