### ISSUE TITLE
NPM version is updated to 1.4.1 but not in releases

### ISSUE THREAD

**Issue by onurusluca** [highcharts/highcharts-vue#237]
I can see that I can update to   `"highcharts-vue": "^1.4.1"` so I did but without changing any code at all, I get the following error:

For using `chart.showLoading()` or `chart.hideLoading()`, getting `chart.value.chart.showLoading is not a function` . 

Is 1.4.1 not official? A mistake?

For anyone getting same error, just downgrade to 1.4.0.

**Comment by jakubSzuminski** [comment]
Thanks for reporting! You're right, it's a bug introduced in 1.4.1.

This has already been reported here: https://github.com/highcharts/highcharts-vue/issues/235

It's been fixed on this repository, but not yet published on the npm. We'll publish it as soon as we can.

**Comment by jakubSzuminski** [comment]
Hi, just wanted to let you know that it has been fixed with the latest version (1.4.2). Feel free to use it! :)
Here's a small example: https://codesandbox.io/s/vue-3-composition-api-demo-forked-z0mvhl?file=/src/components/Chart.vue

**Comment by onurusluca** [comment]
@jakubSzuminski Thank you so much for informing me. Appreciate it!
