### ISSUE TITLE
Chart data update alters mouse hover behavior

### ISSUE THREAD

**Issue by 0ip** [highcharts/highcharts-vue#239]
Since 1.4.1, updating a chart's data alters the chart's behavior when hovering over its data points. Specifically, a line series' plot is slightly faded out (see image below), as if several series exist, even if just a single one is defined.

<img width="684" alt="image" src="https://github.com/highcharts/highcharts-vue/assets/757230/ecf1a254-885f-4c25-9bbe-00c1a4a23be8">

I used https://codesandbox.io/s/vue-3-composition-api-demo-forked-286m7d and cycled between version 1.4.0 and 1.4.2 to reproduce this problem.

**Comment by MatLeRock** [comment]
Also options like _crosshair_ wont show up anymore when updating. Same on version 1.4.2. Everythingthing seems fine on v1.4.0.

**Comment by jakubSzuminski** [comment]
I've prioritized this issue and I'm currently working on it. This will be solved within the next release.
