### ISSUE TITLE
Support for Dashboards

### ISSUE THREAD

**Issue by skspade** [highcharts/highcharts-vue#242]
I am not sure if this wrapper supports the dashboard component. See: https://www.highcharts.com/docs/dashboards/your-first-dashboard

If it does.. then I will happily open a PR to update the README with instructions. 

Thanks!

**Comment by jakubSzuminski** [comment]
Hi @skspade,

This wrapper does not support **Dashboards**. 

For now there's no official wrapper that allows you to integrate **Dashboards** with **Vue** but you can easily achieve this like in this example: https://codesandbox.io/s/vue3-example-forked-6fh8p7?file=/src/Dashboard.vue 

There are plans to create wrappers for **Dashboards** & **Vue**, but there's no specific ETA that I can give you. But from my current knowledge it will be a seperate repository, not this one (more likely `dashboards-vue`).

If you want to be up-to-date with this issue you can check this website -  https://www.highcharts.com/products/dashboards/
