### ISSUE TITLE
Highchart is not scaled correctly

### ISSUE THREAD

**Issue by sjoshid** [highcharts/highcharts-vue#245]
Hi,
Im having trouble scaling the chart with its parent div. Here's how it look. 
![image](https://github.com/highcharts/highcharts-vue/assets/6751090/7e45386a-1ed5-4188-9fdc-bfe53a6fc98d)

I have observed that the chart scales correctly on x axis. But not on y. You can try that in the [codesandbox link](https://codesandbox.io/p/github/sjoshid/Testing-Gridstack-Issue/draft/ancient-wind?file=%2Fsrc%2FApp.vue%3A9%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cln9j08xx00093b5uxu97htyo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cln9j08xx00033b5uf9tdcttt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cln9j08xx00063b5ucdy2se6b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cln9j08xx00083b5uyuafmka9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cln9j08xx00033b5uf9tdcttt%2522%253A%257B%2522id%2522%253A%2522cln9j08xx00033b5uf9tdcttt%2522%252C%2522activeTabId%2522%253A%2522cln9j0exs00563b5uydu0bzs9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln9j08xw00023b5ux8jrlzsg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522cln9j0exs00563b5uydu0bzs9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FHighcharts.vue%2522%252C%2522id%2522%253A%2522cln9jdpsj01d93b5uvvg9sryd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cln9j08xx00083b5uyuafmka9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln9j08xx00073b5u0xwcoklf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cln9j08xx00083b5uyuafmka9%2522%252C%2522activeTabId%2522%253A%2522cln9j08xx00073b5u0xwcoklf%2522%257D%252C%2522cln9j08xx00063b5ucdy2se6b%2522%253A%257B%2522id%2522%253A%2522cln9j08xx00063b5ucdy2se6b%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln9j08xx00043b5uvj9u327n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cln9j08xx00053b5umnxtouj5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cln9ixbrv0014e7i049b12ek2%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cln9j08xx00053b5umnxtouj5%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

What can I do to remove the scrollbars?

FYI: the chart is wihin a [Gridstack](https://gridstackjs.com).

**Comment by jakubSzuminski** [comment]
Hi,

Thanks for reporting @sjoshid.

The problem you're encountering is not related to `highcharts-vue`, but more to `highcharts` and how the `chart.height` is established.

I've prepared a simple override of the `getChartSize` function which solves the problem. 

Please let me know if that works for you.

**Demo:** https://codesandbox.io/p/github/sjoshid/Testing-Gridstack-Issue/csb-6dhn3n/draft/peaceful-gwen?file=%2Fsrc%2FApp.vue%3A5%2C1

**Comment by sjoshid** [comment]
Thanks for creating a fix @jakubSzuminski. 

Upon doing a Google search, it seems many people have a problem with `relfow()` and `setSize()` with no particular fix to the problem I mentioned. 

Do you think it makes sense to have this (your solution) optional in HV where a chart always scales its container?
