### ISSUE TITLE
Problem with using module exporting and highcharts-more in composition API vue 3 and with script setup

### ISSUE THREAD

**Issue by oghme** [highcharts/highcharts-vue#250]
Hi,

I get an error when I try to create a component in composition API Vue 3 with script setup. Here is my component :

![image](https://github.com/highcharts/highcharts-vue/assets/128141590/294d6cec-5207-4adf-974c-683bd123c496)

![image](https://github.com/highcharts/highcharts-vue/assets/128141590/7763e0bb-e22b-4a65-8c1c-069c21d7ad5e)

This is the error that appears on my page : 

`[Vue warn]: Component is missing template or render function. 
  at <Anonymous class="hc" options= {chart: {…}, title: {…}, pane: {…}, xAxis: {…}, yAxis: {…}, …} > 
  at <SpiderwebChart title="Ceci est un test !!!" x-data= (6) ['Sales', 'Marketing', 'Development', 'Customer Support', 'Information Technology', 'Administration'] y-data= (2) [{…}, {…}] > 
  at <DropDownSearchPage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > > 
  at <RouterView> 
  at <DemoPage>`

If you have a way to solve this problem that would be great. Thank you in advance for your answers.

**Comment by oghme** [comment]
Hi,

Thank you for your reply. I've identified my problem and found a solution. You shouldn't import highcharts with this name in component (in my exemple `SpiderwebChart.vue`) :

`import Highcharts from "highcharts";` as in the examples

But put another name like this :

`import hc from "highcharts";`

For more information here is my [code](https://codesandbox.io/p/sandbox/keen-waterfall-vy3yts?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clogw27d600082v6iwfkfyymc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clogw27d600032v6idqgy9et8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clogw27d600052v6ib53gd4wm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clogw27d600072v6i41mwhbqf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clogw27d600032v6idqgy9et8%2522%253A%257B%2522id%2522%253A%2522clogw27d600032v6idqgy9et8%2522%252C%2522activeTabId%2522%253A%2522clogw4z6x00gv2v6i8jvzxjms%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FSpiderwebChart.vue%2522%252C%2522id%2522%253A%2522clogw4z6x00gv2v6i8jvzxjms%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522clogw9zho018d2v6i0vqkcl2g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522id%2522%253A%2522clogws7l001sz2v6iuoe3e1wt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clogw27d600072v6i41mwhbqf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clogw27d600062v6itrra6qs0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clogw27d600072v6i41mwhbqf%2522%252C%2522activeTabId%2522%253A%2522clogw27d600062v6itrra6qs0%2522%257D%252C%2522clogw27d600052v6ib53gd4wm%2522%253A%257B%2522id%2522%253A%2522clogw27d600052v6ib53gd4wm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clogw27d600042v6igc8edfks%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clogw27d600042v6igc8edfks%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by jakubSzuminski** [comment]
Thanks! You're absolutely right - by default, `HighchartsVue` registers the `Highcharts` component which was the cause of the naming conflict. I'm glad that you've found the solution.
