### ISSUE TITLE
demo_vue3 undable to run

### ISSUE THREAD

**Issue by Com4inDev** [highcharts/highcharts-vue#255]
Hi, 
I am working on vue3 composition api <script setup>.

And current version for highcharts are    
"highcharts": "^11.2.0",
"highcharts-vue": "^1.4.3",

Tried to use spline chart starting with series line 1 and update it when user click a btn.
 
I tried 
 selectedSeries.update({
        lineWidth: chart.bold ? 10 : 2,
 });

and checked the chart series's lineWidth changed to 10. But the chart didn't change.
Tried with chart.redraw() but without effect.

How to change the linewidth on vue3 highcharts-vue? 
Thanks.

**Comment by Com4inDev** [comment]
.

**Comment by jakubSzuminski** [comment]
@Com4inDev do I understand correctly that you've already managed to find a solution to this problem?
