### ISSUE TITLE
Upgrading to Vue 3.4.5 breaks the charts

### ISSUE THREAD

**Issue by Kjir** [highcharts/highcharts-vue#256]
When I upgrade to Vue 3.4.5 the charts stop working.
The options are pretty simple, in fact even with just the highcharts options and no other props, it still breaks:

```html
<highcharts
  :options="histogramOptions"
   ></highcharts>
```

![image](https://github.com/highcharts/highcharts-vue/assets/64094/07cb133f-7b11-4477-97f1-1f6fc8fc7442)

From what I could gather, the `chartContainer` ref is still `null` when the `onMounted` is called. I am not entirely sure why this changes from Vue 3.3 to vue 3.4

**Comment by Kjir** [comment]
Here is the simplest reproduction: https://stackblitz.com/edit/vitejs-vite-k8kyr7?file=src%2FApp.vue

Downgrading to Vue 3.3 fixes the issue

**Comment by damisparks** [comment]
@Kjir, I had the same issue with `3.4.5`.
I tested with `3.4.3` and `3.4.4`, and it works.

```json
"highcharts": "11.2.0",
"highcharts-vue": "1.4.3",
"vue": "^3.4.4",
```

**Comment by maprangsoft** [comment]
I have the same problem after upgrade nuxt to latest version and vue upgrade to 3.4.5

**Comment by manniL** [comment]
@maprangsoft You can simply pin vue to 3.4.4 via overrides

**Comment by jakubSzuminski** [comment]
It seems to be related to the latest Vue update which might have broken something. Here's an issue: https://github.com/vuejs/core/issues/10012

I will try to investigate this issue and see if any sensible fix can be proposed. I will keep you posted.

**Comment by jakubSzuminski** [comment]
Until Vue team solves this problem or until I do it on the _highcharts-vue_ package, here's a simple `/highcharts-vue` folder that you can use in your projects which should work with `Vue@3.4.5`: https://stackblitz.com/edit/vitejs-vite-9fottc?file=src%2Fhighcharts-vue%2Findex.js

This `highcharts-vue/index.js` exports the exact same logic as the `highcharts-vue` package, but the issue related to `TypeError: can't access property 'nodeName'` does not arise.

Please let me know if that works for you @maprangsoft @damisparks @Kjir.

I'm investigating this problem and testing out different potential solutions, but in the meantime feel free to use the example that I've linked.

**Comment by dariel87** [comment]
> Until Vue team solves this problem or until I do it on the _highcharts-vue_ package, here's a simple `/highcharts-vue` folder that you can use in your projects which should work with `Vue@3.4.5`: https://stackblitz.com/edit/vitejs-vite-9fottc?file=src%2Fhighcharts-vue%2Findex.js
> 
> This `highcharts-vue/index.js` exports the exact same logic as the `highcharts-vue` package, but the issue related to `TypeError: can't access property 'nodeName'` does not arise.
> 
> Please let me know if that works for you @maprangsoft @damisparks @Kjir.
> 
> I'm investigating this problem and testing out different potential solutions, but in the meantime feel free to use the example that I've linked.

thank you very much, it works.

**Comment by sporritt** [comment]
Vue 3.4.6 is out now, which fixes these issues.

**Comment by damisparks** [comment]
@sporritt I can confirm it works on  `"vue": "^3.4.6"`. 
Anyway, I upgrade my vue version to `"vue": "^3.4.13"`

**Comment by damisparks** [comment]
> > Until Vue team solves this problem or until I do it on the _highcharts-vue_ package, here's a simple `/highcharts-vue` folder that you can use in your projects which should work with `Vue@3.4.5`: https://stackblitz.com/edit/vitejs-vite-9fottc?file=src%2Fhighcharts-vue%2Findex.js
> > This `highcharts-vue/index.js` exports the exact same logic as the `highcharts-vue` package, but the issue related to `TypeError: can't access property 'nodeName'` does not arise.
> > Please let me know if that works for you @maprangsoft @damisparks @Kjir.
> > I'm investigating this problem and testing out different potential solutions, but in the meantime feel free to use the example that I've linked.
> 
> thank you very much, it works.

The solution worked for me as well.

**Comment by damisparks** [comment]
@maprangsoft vue has new versions. See the 👉🏾 [Releases](https://github.com/vuejs/core/releases)

**Comment by Kjir** [comment]
The new version of Vue fixes the issue, the problem can be considered resolved!

**Comment by ayhanfuat** [comment]
> Anyway, I upgrade my vue version to `"vue": "^3.4.13"`

I see the same error in 3.4.13. For me only 3.4.6, 3.4.7 and 3.4.8 work. Anything above that gives the same error.

**Comment by sstenn** [comment]
Seems broken again in `highcharts-vue` version `^2.0.1`

```
"vue": "^3.4.26",
"highcharts": "^11.4.1",
"highcharts-vue": "^2.0.1"
```
