### ISSUE TITLE
issue with types in 2.0.0

### ISSUE THREAD

**Issue by b-maslennikov** [highcharts/highcharts-vue#259]
I started getting this error in VSC and during the build since updated to 2.0.0

```
Argument of type '{}' is not assignable to parameter of type 'Partial<{}> & Omit<{ readonly constructorType?: string | undefined; readonly options: Options; readonly callback?: ChartCallbackFunction | undefined; readonly updateArgs?: ChartUpdateArgs | undefined; readonly highcharts?: typeof import("...'.
  Property 'options' is missing in type '{}' but required in type 'Omit<{ readonly constructorType?: string | undefined; readonly options: Options; readonly callback?: ChartCallbackFunction | undefined; readonly updateArgs?: ChartUpdateArgs | undefined; readonly highcharts?: typeof import("...'.ts-plugin(2345)
highcharts-vue.d.ts(7, 5): 'options' is declared here.
```

![image](https://github.com/highcharts/highcharts-vue/assets/15647102/f27d0036-11cb-4f25-94cd-86f208bb1b8f)

`<loading-bar />` is my (custom) component. it's defined globaly. it does not use highcharts-vue

**Comment by b-maslennikov** [comment]
![image](https://github.com/highcharts/highcharts-vue/assets/15647102/cb62abfe-11fe-48a5-92dd-290aea73b3c8)
one more custom component

**Comment by jszuminski** [comment]
Thanks for reporting! You're absolutely right. I've prepared a simple fix, could you please check if this works as expected?

```
[package.json]
"dependencies": {
    "highcharts": "10.3.3",
    "highcharts-vue": "https://github.com/highcharts/highcharts-vue.git#bug/259-global-types-problem"
  },
```

**Comment by b-maslennikov** [comment]
checked PNPM fix - works perfect to me
thanks

**Comment by jszuminski** [comment]
I'm reopening this issue for now as I need to publish it to npm with v2.1.0 :)

**Comment by jszuminski** [comment]
Published v2.0.1 on npm, this should no longer be a problem. Please feel free to report any more issues in case you find any, I will try to solve them asap.

**Comment by b-maslennikov** [comment]
hmm. latest version on npm is still 2.0.0

**Comment by jszuminski** [comment]
I've authenticated the `npm publish` now and it should be there in the registry.
<img width="768" alt="Screenshot 2024-03-15 at 11 28 45" src="https://github.com/highcharts/highcharts-vue/assets/70104233/c74721b2-a708-4f8a-b65e-0df63f091496">

**Comment by b-maslennikov** [comment]
perfect. thanks mate
