### ISSUE TITLE
[Question] Use highcharts plugin

### ISSUE THREAD

**Issue by Taxman972** [highcharts/highcharts-vue#26]
Hi,

It that possible to use [highcharts plugins](https://www.highcharts.com/products/plugin-registry) especially the [motion plugin](https://www.highcharts.com/products/plugin-registry/single/40/Motion) with highcharts-vue ?

**Comment by Taxman972** [comment]
Solved by adding this code like the others officials modules
<pre>
'use strict';
(function (factory) {
    if (typeof module === 'object' && module.exports) {
        module.exports = factory;
    } else {
        factory(Highcharts);
    }
}(function (Highcharts) {
    // Motion plugin code
}));
</pre>

After that just import like all others modules.

**Comment by mzhukovs** [comment]
nvm the issue was with the href for the fontawesome css - your code helped me, thanks! @Taxman972
