### ISSUE TITLE
Issue with flamechart in Vue

### ISSUE THREAD

**Issue by jjaramillom** [highcharts/highcharts-vue#261]
I wasn't sure where to open the issue, so I also opened [one in Highcharts repo](https://github.com/highcharts/highcharts/issues/20945)

#### Expected behaviour

A chart with the provided data 
![image](https://github.com/highcharts/highcharts/assets/31043682/7a747f85-a3f6-40cb-aa6f-24579426d190)

#### Actual behaviour
No chart. If I inspect the HTML elements I see an `<svg/>` element but with no actual content.
![image](https://github.com/highcharts/highcharts/assets/31043682/c28af2f3-2319-46d4-b382-2cc7a5a0439a)

#### Live demo with steps to reproduce
[Working version with vanilla JS](https://codepen.io/jjaramillom/pen/poBpKgM?editors=0010)
[Failing version with Vue](https://codesandbox.io/p/sandbox/cranky-haze-8vh89r?file=%2Fpackage.json%3A12%2C21)

#### Product version
Highcharts 11.4.0

#### Affected browser(s)

Chrome

**Comment by jszuminski** [comment]
Thanks for reporting!

The difference between the working example and the one reproduced in Vue is that you have not added appropriate modules in the latter one.

If you import and apply the `highcharts-more` module (and, potentially `sunburst` if you need it somewhere), you will get a non-empty, working chart: https://codesandbox.io/p/sandbox/lively-fire-pznhp5?file=%2Fsrc%2Fcomponents%2FFlamechart.vue

Here's a section in the docs about this: https://github.com/highcharts/highcharts-vue?tab=readme-ov-file#importing-highcharts-modules

Please let me know if importing & applying modules solved it for you.

**Comment by jjaramillom** [comment]
Thanks @jszuminski. Somehow when I tried it it didn't work, maybe some env issue (I even had it commented out in my demo). Now it's working fine.
I'm just wondering, in my actual project it was working kind of flaky. Any idea why would this be?

Anyway, thanks a lot.

**Comment by jjaramillom** [comment]
The chart we have was being rendered sometimes, while sometimes it wasn't being rendered (in a random fashion), I just wanted to know if this is a known behavior or not. Anyway, the issue is solved now, so nothing to worry about.
