### ISSUE TITLE
Chart breakage in vue3.5xx version

### ISSUE THREAD

**Issue by vss2026** [highcharts/highcharts-vue#266]
There is an issue with charts breaking in versions like vue 3.4.8, they display fine in this version but our project needs to use 3.5.x

vue@3.5.6

highcharts-vue@1.4.3

highcharts@11.2.0

![image](https://github.com/user-attachments/assets/a7f1499a-8f07-4db8-9814-d9daac829c9a)

**Comment by jszuminski** [comment]
Closing as a duplicate of: https://github.com/highcharts/highcharts-vue/issues/256
