### ISSUE TITLE
How to use with dynamic series data

### ISSUE THREAD

**Issue by OCKOTradoc** [highcharts/highcharts-vue#27]
I can't seem to find a way to get the chart to draw when I have to calculate the series data from an ajax call. The ajax call works fine and I get the data just fine but can't seem to draw/update the chart with this data.

**Comment by Denyllon** [comment]
Thank you for contacting us.
Actually, the Issues tab on this GitHub repository is our bugtracker, so please contact our support team using one of support channels (Highcharts Forum, StackOverflow, or just sending email to support@highcharts.com)

P.S
The process of implementing that in correct way is simple. Let's assume, that you have some `chartData` in your component, so actually just need to update it in every AJAX call, then your chart should automatically change its data.
