### ISSUE TITLE
Solid guage refresh when receives new data (point value)

### ISSUE THREAD

**Issue by bensladden** [highcharts/highcharts-vue#28]
I am having issues with my solid gauge component where every time it receives new data it re-draws from 0. Please see sandbox link below:
https://codesandbox.io/s/n0no0jky1l

The desired behavour im trying to achieve is shown here:
https://www.highcharts.com/demo/gauge-solid

**Comment by bensladden** [comment]
Thanks Denyllon,

This solved my issue with the gauge, im however now having issues with pie charts (using the update method) now as reported here: https://forum.highcharts.com/highcharts-usage/highcharts-vue-wrapper-t41012

**Comment by Denyllon** [comment]
Thank you for your informations. It's directly related with #29 issue.

**Comment by TorsteinHonsi** [comment]
@bensladden I think https://github.com/highcharts/highcharts/issues/8960 also fixes the solid gauge animation feature. You can now update the gauge with `Series.update()` and a full data setting. See http://jsfiddle.net/highcharts/3jb0gekv/2/.

**Comment by Denyllon** [comment]
Unfortunately fix included above, doesn't solve the problem. It is caused by passing the same `chart.type` through the `Chart.update()` function. Problem is directly related with [this](https://github.com/highcharts/highcharts/issues/9197) Highcharts issue.
