### ISSUE TITLE
No animation on pie chart using update method and Vue Wrapper

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts-vue#29]
_From @bensladden on September 13, 2018 2:25_

#### Expected behaviour
It is expected that the charts will animate as shown in this example:
http://jsfiddle.net/0wp4ngy9/

#### Actual behaviour
No animation, the pie chart instantly changes to the most recent values. This also appears to be the case for bar and column charts

#### Live demo with steps to reproduce
https://codesandbox.io/s/y0x2561vk9

#### Product version
Highcharts 6.1.0
highcharts-vue 1.0.4
vue ^2.5.2

_Copied from original issue: highcharts/highcharts#8942_

**Comment by Denyllon** [comment]
I'll take a closer look on that as soon as possible.

**Comment by TorsteinHonsi** [comment]
There was a bug in `Series.update()`, causing animation to always be turned off. See https://github.com/highcharts/highcharts/issues/8960. Please try out this fix before diving into the vue wrapper.

**Comment by bensladden** [comment]
No Joy unfortunately: https://codesandbox.io/s/ykp4ql9q1x
Also using these product versions:
Highcharts 6.1.3
highcharts-vue 1.2.0
vue ^2.5.2

**Comment by Denyllon** [comment]
Hi @bensladden,

First of all, I need to apologize for the silence in this topic, and really thank you for your patience and understanding.

The problem is, that the object passed to the `update()` function, includes the `chart.type` set, equal to the same value as it was before, what causes the problem (but it shouldn't be like that). The issue is already reported on our Highcharts repository here: https://github.com/highcharts/highcharts/issues/9197.

At this moment, to workaround it, please delete the `chart.type` from the chart configuration object, and define the `series.type`. Additionally, every time when you will update component `chartOptions.series` object, it shouldn't have the `type` defined again. I've prepared working example to show, how it should be done: https://codesandbox.io/s/8kzo761x4j

Hope that helps you.

**Comment by bensladden** [comment]
Thanks for the update. Ill test this out and see how i go

**Comment by petterw03** [comment]
Defining the type in the series instead of in the chart config makes no difference to me - I still see no animations.

**Comment by Denyllon** [comment]
Hello @petter03,

In which way you defined your chart options, just through placing it within the returned `data` property or used `computed` properties? Here is the example which shows how it should be implemented in order to make animation works correctly: https://codesandbox.io/s/qq27v70ny4

Best regards!
