### ISSUE TITLE
Add indicators in the highstock demo

### ISSUE THREAD

**Issue by scosc** [highcharts/highcharts-vue#3]
I've been struggling to get the indicators series to work on the highstock example. Still no luck. Please add indicators to the highstock example.

**Comment by hemanth-sp** [comment]
did you done?

**Comment by Denyllon** [comment]
Hi @hemanth-sp ,

Thank you for contacting us. 
Here you can see how the indicators module can be used with this wrapper: https://codesandbox.io/s/highcharts-vue-demo-forked-56zoq
Hope it dispels your doubts.

Kind regards!
