### ISSUE TITLE
HighCharts and Vue virtual dom

### ISSUE THREAD

**Issue by dcvice1967** [highcharts/highcharts-vue#37]
How does this wrapper integrate highcharts with the Vue virtual dom? Does Highcharts.js manipulate the dom directly?

**Comment by Denyllon** [comment]
Thank you for contacting us.
Highcharts is just loaded as a third-party library in your application, so yes, it directly manipulates the DOM elements.

Kind regards!

**Comment by Denyllon** [comment]
Closing the issue, due to lack of activity. Please reopen it in case of any further questions.
