### ISSUE TITLE
Highcharts error #17

### ISSUE THREAD

**Issue by dharmatv** [highcharts/highcharts-vue#38]
when i am developing bubble chart in vue it showing error, please see below link

https://snag.gy/M3LVUk.jpg

**Comment by KacperMadej** [comment]
Hi @dharmatv 

Please share chart configuration and list of loaded Highcharts modules.
You might be trying to create a series type that requires additional file or you might have a typo in series type.

**Comment by dharmatv** [comment]
data(){ 
return {
series: [{
        type: bubble,
        colorByPoint: true,
        data: [{ "x": 95, "y": 95, "z": 13.8, "name": "BE", "country": "Belgium" },
            { "x": 86.5, "y": 102.9, "z": 14.7, "name": "DE", "country": "Germany" }]
    }],
title: {
        text: 'testing'
    }
}
}

Thanks for reply mr. KacperMadej, and i have a doubt please tell me what it means list of loaded modules, i think i had use only highcharts npm that's all. and also please find out above one is the chrt configuration

**Comment by pawelfus** [comment]
Hi @dharmatv 

Please show how you load modules. `bubble` series requires `highcharts-more` module: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

For example, you should have:
```javascript
import Highcharts from 'highcharts'
import highchartsMore from 'highcharts/highcharts-more'

highchartsMore(Highcharts)
```

**Comment by dharmatv** [comment]
Hey @pawelfus Thanks Bro

**Comment by pawelfus** [comment]
Yes, it's the same for funnel:

```javascript
import Highcharts from 'highcharts'
import highchartsMore from 'highcharts/highcharts-more'
import highchartsFunnel from 'highcharts/modules/funnel'

highchartsMore(Highcharts);
highchartsFunnel(Highcharts);
```

**Comment by tspesh** [comment]
> Hi @dharmatv
> 
> Please show how you load modules. `bubble` series requires `highcharts-more` module: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules
> 
> For example, you should have:
> 
> ```js
> import Highcharts from 'highcharts'
> import highchartsMore from 'highcharts/highcharts-more'
> 
> highchartsMore(Highcharts)
> ```

I feel like this should make its way into the docs. On a level it's super simple and maybe i'm just tired, but it took me forever to track this down.

**Comment by KacperMadej** [comment]
@tspesh 
It's in docs here: https://api.highcharts.com/highcharts/plotOptions.bubble

> Requires `highcharts-more.js`.

Please let us know where would be a better or an additional place for this info - where have you expected to find this info?

**Comment by mehmetpolat** [comment]
> ```js
> import highchartsMore from 'highcharts/highcharts-more'
> import highchartsFunnel from 'highcharts/modules/funnel'
> 
> highchartsMore(Highcharts);
> highchartsFunnel(Highcharts);
> ```

`import HighchartsVue from 'highcharts-vue'
import highchartsMore from 'highcharts/highcharts-more'
import highchartsFunnel from 'highcharts/modules/funnel'
highchartsMore(HighchartsVue);

highchartsFunnel(HighchartsVue);
// HighChart using
Vue.use(HighchartsVue);`

but i get the error "highcharts-more.js?33c6:8 Uncaught TypeError: Cannot read property 'parts/Globals.js' of undefined"

**Comment by pawelfus** [comment]
@mehmetpolat 

Did you load Highcharts module? Just like in docs: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

```
import Highcharts from 'highcharts' 

import highchartsMore from 'highcharts/highcharts-more'
import highchartsFunnel from 'highcharts/modules/funnel'

highchartsMore(Highcharts);
highchartsFunnel(Highcharts);
```

Extra question: which version of Highcharts do you have?

**Comment by akkhan20** [comment]
> Yes, it's the same for funnel:
> 
> ```js
> import Highcharts from 'highcharts'
> import highchartsMore from 'highcharts/highcharts-more'
> import highchartsFunnel from 'highcharts/modules/funnel'
> 
> highchartsMore(Highcharts);
> highchartsFunnel(Highcharts);
> ```

Same Error:
```[Vue warn]: Error in mounted hook: "Error: Highcharts error #17: www.highcharts.com/errors/17"```

```
import VueHighcharts from 'vue2-highcharts';
import Highcharts from 'highcharts';

import highchartsMore from 'highcharts/highcharts-more';
import highchartsFunnel from 'highcharts/modules/funnel';

highchartsMore(Highcharts);
highchartsFunnel(Highcharts);
```
Code:
```
data: () => ({
    options: {
      chart: {
        type: 'funnel',
      },
      title: {
        text: 'Sales funnel',
      },
      plotOptions: {
        series: {
          dataLabels: {
            enabled: true,
            format: '<b>{point.name}</b> ({point.y:,.0f})',
            softConnector: true,
          },
          center: ['40%', '50%'],
          neckWidth: '30%',
          neckHeight: '25%',
          width: '80%',
        },
      },
      legend: {
        enabled: false,
      },
      series: [{
        name: 'Unique users',
        data: [
          ['Website visits', 15654],
          ['Downloads', 4064],
          ['Requested price list', 1987],
          ['Invoice sent', 976],
          ['Finalized', 846],
        ],
      }],

      responsive: {
        rules: [{
          condition: {
            maxWidth: 500,
          },
          chartOptions: {
            plotOptions: {
              series: {
                dataLabels: {
                  inside: true,
                },
                center: ['50%', '50%'],
                width: '100%',
              },
            },
          },
        }],
      },
    },
  }),
```

**Comment by Denyllon** [comment]
@mehmetpolat 
The problem is with the way of how you calling the module, because you are passing the `HighcahrtsVue`component as the argument, instead of Highcharts instance. To make it much clear, you have to call it like:
```js
import Highcharts from 'highcharts'
import highchartsMore from 'highcharts/highcharts-more'
import highchartsFunnel from 'highcharts/modules/funnel'
import HighchartsVue from 'highcharts-vue'

highchartsMore(Highcharts);
highchartsFunnel(Highcharts);

Vue.use(HighchartsVue);
```

@akkhan20 
Please note, that you're not running our official Highcharts wrapper for Vue, but the `vue2-highcharts` which is not maintained by Highsoft. I recommend you to install the `highcharts-vue` package, instead of mentioned `vue2-highcharts`, what certainly should resolve the problem with the error.

Kind regards!

**Comment by akkhan20** [comment]
@mehmetpolat yes done that already and the issues were on our end, thanks for responding though :)

**Comment by timothymarois** [comment]
This should be added to the documentation, I almost submitted a new issue regarding how to do this. It is not clear how to add all of these additional modules in the documentation. Thanks for everyone's responses to this thread, it has helped a lot.

**Comment by Denyllon** [comment]
@timothymarois It is already added to the documentation in the [Importing Highcharts modules](https://github.com/highcharts/highcharts-vue#importing-highcharts-modules) section. All modules should always be loaded in the same way described in the documentation:

> To use any of Highcharts modules, you're obligated to import that module to your file, as well as Highcharts package itself and add that module by passing Highcharts to it, for example:
>
> ```js
> import Highcharts from 'highcharts'
> import exportingInit from 'highcharts/modules/exporting'
> 
> exportingInit(Highcharts)
> ```

Do you have ay suggestion of how it could be described much understandable than currently?
