### ISSUE TITLE
Having two highcharts components on one page results in second chart axis x and y disappearance on second render

### ISSUE THREAD

**Issue by lauri108** [highcharts/highcharts-vue#4]
I've created a wrapper component that has the highcharts tag in its template:
`<highcharts :options='chartOptions' ref='lineCharts'></highcharts>`
The parent component is using that wrapper like so:
`<planned-vs-actual-graph chosenMetric='metricID' />`

I've got a VueX store that maintains global query parameters, and the chart does an Axios based API call when certain VueX store params change. All this works fine.

My problem appears when I add another wrapper onto the parent component:
`<planned-vs-actual-graph chosenMetric='metric1' />`
`<planned-vs-actual-graph chosenMetric='metric2' />`

The first time both graphs render fine, and the chosenMetric is being used properly to populate the title, the Y axis and as an API query parameter. Data comes back correctly, and clearly populates correctly upon the first API query. Both graphs render as intended.

The problem is that the second time around, one of the graphs only updates its data points, but does not update its axis x and axis y. Also the tooltip hover looks broken. The error in my console:

> TypeError: d[h].update is not a function
>     at eval (highcharts.js?e74e:288)
>     at Array.forEach (<anonymous>)
>     at a.each (highcharts.js?e74e:28)
>     at e.updateData (highcharts.js?e74e:288)
>     at e.setData (highcharts.js?e74e:289)
>     at e.update (highcharts.js?e74e:336)
>     at eval (highcharts.js?e74e:330)
>     at Array.forEach (<anonymous>)
>     at a.each (highcharts.js?e74e:28)
>     at eval (highcharts.js?e74e:330)

This error is not consistent, the disappearing axis jumps between graph1 and graph 2.

**Comment by Denyllon** [comment]
Hi @lauri108,
Thank you for your report. Could you provide me with minimal working live copy of your project and detailed steps to reproduce it? Would be good to reproduce it using any type of sandbox. I need to exactly know what is the difference between the old chart configuration object and the new one (before the error thrown in console) or what part of that object has changed?

Could be related to the issue reported few days ago on pure Highcharts library repository:
https://github.com/highcharts/highcharts/issues/8355

**Comment by lauri108** [comment]
@Denyllon I'll try to recreate this error in a simplified version that loads data from static JSON files instead. Thanks!

**Comment by lauri108** [comment]
@Denyllon an essential bit of added info: After disabling the Boost module, the rendering works fine!
in my main.js I've been doing this:
```
import HighchartsVue from 'highcharts-vue'
import Highcharts from 'highcharts'
import boost from 'highcharts/modules/boost'
Vue.use(HighchartsVue)
boost(Highcharts)
```
Using the Boost module this way improved the render performance of a single chart significantly (I work with data sizes of 3 series over 10,000 points each), but now that I'm using two charts, using it kills the Y and X axis randomly on either graph when using two graphs. 

I've tested with and without the Boost module and am getting a consistent result of both graphs' X and Y axis rendered correctly when Boost is disabled, and a consistent result of either graph's X and Y axis, as [previously described](https://github.com/highcharts/highcharts-vue/issues/4#issue-326013446).

**Comment by Denyllon** [comment]
Hi @lauri108,

Thank you for more detailed info. It allows me to get closer to the source of the problem. However, as I said before it would be great to see the issue on some live example, because it's hard to guess what exactly causing this kind of problems, so I renew my request of it.

Best regards!

**Comment by Denyllon** [comment]
Closing the issue, due to lack of activity. Please reopen it in case of any further questions.
