### ISSUE TITLE
Chart redraw

### ISSUE THREAD

**Issue by tho068** [highcharts/highcharts-vue#40]
Hello

I was wondering if it was possible to access the chart object directly to for example call redraw?

**Comment by Denyllon** [comment]
Hi @tho068,

Of course, it is. Please refer our documentation, exactly the https://github.com/highcharts/highcharts-vue#chart-object-reference.

Best regards!

**Comment by pooja-dure** [comment]
Can anyone please help me to know how to use chart redraw function in highcharts-vue.

**Comment by Denyllon** [comment]
Hi @pooja-dure ,

Sure thing, here is the example: https://codesandbox.io/s/highcharts-vue-demo-ymzns

Kind regards!

**Comment by pooja-dure** [comment]
Hey @Denyllon,

Thanks for the help.
