### ISSUE TITLE
Could not find a declaration file for module 'highcharts-vue'

### ISSUE THREAD

**Issue by ijandc** [highcharts/highcharts-vue#48]
I exec the command below:
```
yarn add highcharts
yarn add highcharts-vue
```

and then:
```
import Highcharts from 'highcharts'
import highchartsVue from 'highcharts-vue'
Vue.use(HighchartsVue)
```

it show the errors below:
```
 Could not find a declaration file for module 'highcharts-vue'. '/Users/jcmac/TC/fms-front-v2/node_modules/highcharts-vue/dist/module/highcharts-vue.min.js' implicitly has an 'any' type.
  Try `npm install @types/highcharts-vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'highcharts-vue';`
```
How to solve this problem please?

**Comment by ijandc** [comment]
the module had been installed successfully

**Comment by ijandc** [comment]
for what?
close?

**Comment by sebastianbochan** [comment]
Hi @ijandc,
You wrote that module has been installed correctly, so I thought that all worked properly. Am I wrong and problem is still valid?

**Comment by ijandc** [comment]
i mean that i installed the module successfully,but still get the error,hah
please open the issue

**Comment by sebastianbochan** [comment]
Thank you for the feedback. I reopened and assigned the developer who is responsible for this wrapper.

**Comment by ijandc** [comment]
@sebastianbochan okay，thank u

**Comment by Denyllon** [comment]
Hello @ijandc ,

Thank you for contacting us.
A Work on the type declarations files of this (and other official wrappers) package is currently in progress. Due to the Christmas time, a vast majority of people from our company has holidays, so I assume that will be ready to use, only at the beginning of the year. I recommend you to watch this topic, and calmly wait for the updates in this repository.

Kind regards!

**Comment by ChadRoberts21** [comment]
I don't think highcharts-vue pulls down highcharts(core/standard) as a dependency, manually adding it seem to fix the issue for me

**Comment by Denyllon** [comment]
Hi @ChadRoberts21 

What do you mean exactly?. This wrapper has `highcharts` package defined as `peerDependency`, so it should be added manually into every project that uses the wrapper.

Kind regards!

**Comment by ChadRoberts21** [comment]
@denyllon, Don't now how it happened but the high charts dependency was not pulled down with the Vue wrapper when installed via the Vue Ui I have not check if the same thing happens though npm

**Comment by Denyllon** [comment]
@ChadRoberts21 As I said before, Highcharts are defined in `peerDependency`, so you need to install `highcharts` and `highcharts-vue` separately. You can read about the requirements in documentation [here](https://github.com/highcharts/highcharts-vue#requirements)

Best regards!

**Comment by torueck** [comment]
It's been a while since Christmas holidays. Have you made any progress in providing a type declaration file?

**Comment by aacassandra** [comment]
yeah same issue. when i'm try using vue typescript. is there a demo vue application with typescript? help is really very much appreciated thanks.

**Comment by Denyllon** [comment]
Hello @torueck and @aacassandra ,

Whole wrapper enhancement is almost ready to release, so it should be available to download in few days. Upcoming version will have basic type declaration, which will resolve the issue with throwing the error mentioned above.

Kind regards!
