### ISSUE TITLE
ie11 support issue

### ISSUE THREAD

**Issue by sjquant** [highcharts/highcharts-vue#49]
highcharts-vue does not support ie11. All your examples are not shown in ie11.
I think this issue needs to be solved quickly.

**Comment by KacperMadej** [comment]
Hi @sjquant 

Thank you reporting about the problem.

**Workaround**: check errors in browser console and fix them like in this demo that works in IE11 - https://jsfiddle.net/BlackLabel/uyb5xL6n/embedded/result,css,html,js (based on https://jsfiddle.net/BlackLabel/ukc2kqnb/)

_Internal note:_
Format like `data() {` is not supported in IE11, but `data: function() {` works fine both in Chrome and IE11 (tested on Win10). JSFiddle limits IE11 to read only, but this is not a problem that we should be concerned about.

**Comment by sjquant** [comment]
Thanks for the quick answer and working example @KacperMadej 
When using single file component, as far as I know, it is compiled(not exactly) by webpack for ie11 to work.
Actually, I solved this issue for myself to create new wrapper using single file component.
And it works when using  `data() {`. In my opinion, it should work when using single file component and using `data() {`

**Comment by sjquant** [comment]
https://codesandbox.io/s/j37rzpjmqv

What I did is just making it into single file component.
But, codesandbox does not support ie11, so this example cannot be seen in ie11 browser. : (

But it works when I did in vue-cli in my local computer.

**Comment by KacperMadej** [comment]
Thank you for the demo.
The support for IE11 in Codesandbox is currently bugged - https://github.com/CompuIves/codesandbox-client/issues/1187
You could try with stackblitz - https://stackblitz.com/edit/vue
