### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by atilkan** [highcharts/highcharts-vue#5]
Please add type definitions.

**Comment by Denyllon** [comment]
Hi @atilkan,

You mean adding definitions to wrapper's properties, or generally for Highcharts? If for Highcharts, please visit this link: https://github.com/highcharts/highcharts/issues/4876

Best regards!

**Comment by atilkan** [comment]
Just for the wrapper. Thanks

**Comment by Denyllon** [comment]
Hi @atilkan,

Please specify more precisely what exactly you expecting and what effect do you need to achieve, because I'm wondering how would you propose to define the types without using TypeScript in the component package?

Best regards!

**Comment by atilkan** [comment]
Afaik you dont have to use typescript. You just add type defination file accordingly. 
It is problematic for projects that use typescript.

**Comment by Denyllon** [comment]
Thank you for your answer. The types of which elements of wrapper should be available in your IntelliSense quick informations? 

Best regards!

**Comment by mzhukovs** [comment]
![image](https://user-images.githubusercontent.com/13161978/50143958-e8a05280-02e8-11e9-9a38-3471f7c2147e.png)

**Comment by Denyllon** [comment]
Hi @mzhukovs,

Latest release of Highcharts (v7) already has their own `d.ts` files for every module, and we're currently working on declarations for Vue wrapper. Stay tuned for repository updates and please calmly wait for it. Should be available soon.

Kind regards!

**Comment by mzhukovs** [comment]
Absolutely, will do. Thanks for the update! @Denyllon
