### ISSUE TITLE
cant rereset the chart

### ISSUE THREAD

**Issue by liuhoi** [highcharts/highcharts-vue#52]
my chart has a array included 50 date，if the array has null , it cant reset the chart it keep old chart and render new data that not null,how can i reset the chart with new array that has null

**Comment by liuhoi** [comment]
i found Highcharts 7.0.2 has restore this BUG,it can redraw null data,thank you

**Comment by sebastianbochan** [comment]
Hi @liuhoi,
Could you prepare a live demo which will allow us to debug it?

**Comment by KacperMadej** [comment]
I think @liuhoi wanted to let us know that the problem is resolved in v7.0.2, so the problem is fixed and this issue could be closed.

@liuhoi Is your problem solved? Can we close this issue?

**Comment by liuhoi** [comment]
i use 7.0.2 solved this issue ,than you
