### ISSUE TITLE
Dynamic data not plotting correctly

### ISSUE THREAD

**Issue by goalstogrowth** [highcharts/highcharts-vue#54]
Changing out the series data plots the new points correctly, but it draws the lines incorrectly. Instead of drawing a line from the last point in the series to the new point, it draws the line from the first point to the new point without erasing the old line in between. Is there a way to force a complete redraw?
![capture](https://user-images.githubusercontent.com/44439918/52754568-f9a7d000-2fc8-11e9-9b81-406096726b85.PNG)

**Comment by goalstogrowth** [comment]
I should probably add that the whole data set has to be updated, not just a single point. Data can be updated at any point across the x-axis and not just the last in the series.

**Comment by Denyllon** [comment]
Hi @goalstogrowth 

Thank you for your report. Could you try produce live example (using CodeSandbox or StackBlitz platform), where the issue occurs? I need to see how exactly are you updating your data.

Best regards!
