### ISSUE TITLE
How to make a chart have a 100% height of parent?

### ISSUE THREAD

**Issue by tzaitoun** [highcharts/highcharts-vue#58]
The height option doesn't work because a percent is relative to its width and not its parent. Thanks.

**Comment by Denyllon** [comment]
Hello @tzaitoun ,

Thank you for your report.
The Issues tab is our bug tracker for this wrapper, so next time, please ask your questions using one of support channels ([Highcharts forum](https://www.highcharts.com/forum/), [StackOverflow](https://stackoverflow.com/) or sending an email to support@highcharts.com).

As the documentation says:
> By default (when null) the height is calculated from the offset height of the containing element, or 400 pixels if the containing element's height is 0.

It follows from the foregoing, that if you will set some height on parent element (containing), then Highcharts set the same value on the chart. I prepared the example where I set it up in a correct way.

Live example: https://codesandbox.io/s/21xz5owkjj

Best regards!
