### ISSUE TITLE
Error in mounted hook: "Error: Highcharts error #17" Gauge

### ISSUE THREAD

**Issue by Mellis84** [highcharts/highcharts-vue#59]
Hi Guys,

I have seen this issue floating about and have followed what other threads have come up with but I'm still struggling to get the gauge chart working in my Vue instance.

Options object:
`      chartOptions: {
        chart: {
          type: 'solidgauge',
          height: '100%',
        },
        title: {
          text: '',
        },
        pane: {
          startAngle: 0,
          endAngle: 360,
          background: [{
            outerRadius: '112%',
            innerRadius: '88%',
            backgroundColor: '#000',
            borderWidth: 0,
          }],
        },
        yAxis: {
          min: 0,
          max: 100,
          lineWidth: 0,
          tickPositions: [],
        },
        plotOptions: {
          solidgauge: {
            dataLabels: {
              enabled: false,
            },
            linecap: 'round',
            stickyTracking: false,
            rounded: true,
          },
        },
        series: [{
          data: [{
            color: '#333',
            radius: '62%',
            innerRadius: '38%',
            y: 50,
          }],
        }],
      },`

Template:
`<highcharts class="gauge" :options="chartOptions"></highcharts>`

JS in Template:
`
import { Chart } from 'highcharts-vue';

export default {
  props: {
    chartOptions: {
      type: Object,
      required: true,
      default: () => {},
    },
  },

  components: {
    highcharts: Chart,
  },
};
`

Instance:
`
import Highcharts from 'highcharts';
import highchartsGauge from 'highcharts/modules/solid-gauge';
import HighchartsVue from 'highcharts-vue';

/*
 * Vue Highcharts
 */
Vue.use(HighchartsVue);
highchartsGauge(Highcharts);
`
I have also tried loading in highcharts more ie: highchartsMore(highcharts);
but that doesn't solve it either, appreciate any help :).

P.S sorry I don't know why the code formatting is jacked in this post :S.

**Comment by Mellis84** [comment]
I had to initialise high charts before all my other plugins in my main app.js file :|

**Comment by tspesh** [comment]
@Mellis84 can you post an example of how you did this?
