### ISSUE TITLE
Dynamic series & data

### ISSUE THREAD

**Issue by shaunc869** [highcharts/highcharts-vue#6]
Hi!

How do add a dynamic series of data properly? Sorry for the basic question but all of the examples assume static data.

**Comment by Denyllon** [comment]
Hi @shaunc869,

There is a simple demo example in the repository which shows how to do it so that the chart reacts on data changes. You can read in the documentation how to run the demo. Here is the direct link: https://github.com/highcharts/highcharts-vue#demo-app
Please take a look on it and its code structure, and then if you would have more questions let us know.

Kind regards!

**Comment by Taxman972** [comment]
Could you provide an example using the data module all my tests to use it fail.
<pre>
data: {
    // csv: document.getElementById('csv').innerHTML, // no data showing
    csvURL : 'https://website/path/to/file/file.csv', // I don't even see an ajax call
    itemDelimiter: ',',
    complete: function (data) {
        console.log(data); // with csv or csvURL // nothing in the console
    }
},
</pre>

**Comment by Denyllon** [comment]
Hi @Taxman972 ,

There is no enough informations and code in your question to deduce what exactly could cause your problems.

> Could you provide an example using the data module all my tests to use it fail.

Sure, here is it: https://codesandbox.io/s/zrk7pv4k3p

Best regards!

**Comment by Taxman972** [comment]
@Denyllon Thanks for the example now it's works.

**Comment by shaunc869** [comment]
Sorry I probably was specific enough, in my case I need to make a call to an API to return a dynamic set of data points for a multi-series graph. Right now I make the get request and when it return I dynamically add series like this:

```
this.theChart.series[0].setData([]);

					this.theChart.series[0].addPoint({
						"color": "#178ACD",
						"x": 0,
						"y": _self.liveCount,
						"name": "Live"
					});

					this.theChart.series[0].addPoint({
						"color": "#23D2BE",
						"x": 1,
						"y": _self.processingCount,
						"name": "Processing"
					});

					this.theChart.series[0].addPoint({
						"color": "#F2326B",
						"x": 2,
						"y": _self.optedCount,
						"name": "Opted Out"
					});

					this.theChart.series[0].addPoint({
						"color": "#FDC131",
						"x": 3,
						"y": _self.unavCount,
						"name": "Unavailable"
					});
```

The issue is I can't add the series until "theChart" exists, which gets populated on call back:

`<highcharts :options="chartOptions" :callback="chartLoaded" style="height:100%;width:100%;position:absolute;padding-right:20px;"></highcharts>`

This works great most of the time, but I notice as I navigate from page to page sometimes the get request returns and tries to populate before the call back fires so the chat isn't ready. But if I try to move the get request into the chart call back sometimes it loads before mounted loads so I the chart won't render. My question is how am I supposed to properly populate the chart using ajax'd data in a multi-series scenario? Thanks a lot for the help!

**Comment by Denyllon** [comment]
hi @shaunc869 ,

Most certainly, the best place to get the data is when the chart is already loaded. Maybe try to move the get request into the chart configuration object to `chart.events.load`. If it won't help you, I'm afraid that it would be necessary to debug your code, so then I will need to see some minimal live example of that issue (with Vue of course).

API Reference: https://api.highcharts.com/highcharts/chart.events.load

Best regards!
