### ISSUE TITLE
Browser hangs when adding points as [x, y] array (Highcharts error #15 thrown)

### ISSUE THREAD

**Issue by epaterlini** [highcharts/highcharts-vue#61]
When I add points (in the form of array of array) to the reactive "options" object, 
the browser hangs and after a while a Vue-warn is thrown:

> 
vue.runtime.esm.js:601 [Vue warn]: You may have an infinite update loop in watcher with expression "options"
found in ... etc ...
Also Highcharts throws error #15 on the console.

The data is correctly sorted.
If I add the points as single y points (no x-y array) it works fine.
What can be the problem?

I'm using Highstock module 7.0.2 in a Vue application.
Vue version 2.5, Highcharts Vue wrapper version 1.2
Browser tested is Google Chrome/chromium

Please help!!!
Thanks a lot

**Comment by epaterlini** [comment]
I'm adding the points from an ajax callback (axios), don't know if it helps.
Btw, I tried also add points with a counter variable as X (always monotonically raising) to test and the error happens, so surely is not a problem of unordered or duplicate items in series.
Can the problem be in the "Object.assign({}, options) in the watcher function?
Don't know if, for strange things, it duplicates the data in the options (is only a tought).

Thank you, 
Emiliano

**Comment by epaterlini** [comment]
I solved by adding the points manually via the standard API function Series.addPoint...but kept the options data reactive.
Don't know if mixing reactive properties with manually added points causes problem...hopefully not :-)

**Comment by KacperMadej** [comment]
Hi @epaterlini 
It might cause some problems - desynchronization between chart options updated through the wrapper and changes done through API calls, but as long you are not getting any errors then it's fine.

Could you create a live demo with the problem? (An online sandbox or a demo app that could be build and debugged)

Do you know points number at the time of the error? Maybe you have reached turboThreshold (defaults to 1000 for most series types)?

**Comment by Denyllon** [comment]
It's hard to deduce what could cause the problem without any code inspection. I prepared the example where I'm adding the points directly to reactive component object in three different ways of data implementation. Everything is working well, so as @KacperMadej said, we need to see the problem on some live example, and try to debug what is happening.

Live example: https://codesandbox.io/s/18n7571n53

Kind regards!

**Comment by matt4682** [comment]
It seems like the browser hanging issue is related to Highcharts 7.0.0, if you upgrade Highcharts in the live example you linked, it starts to hang.

Example: https://codesandbox.io/s/6x76p8n65r

**Comment by epaterlini** [comment]
@matt4682 exactly. Thank you for pointing this out.
For the moment I workaround this by adding points as a single array and using fixed "pointInterval".
But this is far from being ideal...
I hope that someone finds a way to solve this...

Best regards,
Emiliano

**Comment by Denyllon** [comment]
Hello @matt4682 and @epaterlini ,

Thank you for sending the example. Generally, pushing a new value into component data arrays is contrary to Vue conceptions, because it can cause the problems (e.g like above), so that's the reason why we should avoid mutating a component data, always when it's possible.
In order to fix the example you provided, just need to use spread operator and assign new array with existing values and the new one. Please take a look at code and example below:

```js
  mounted() {
    var self = this;

    setInterval(function() {
      self.chartOptions.series[0].data = [
        ...self.chartOptions.series[0].data,
        [++self.counter, Math.random() * 10]
      ];
      self.chartOptions.series[1].data = [
        ...self.chartOptions.series[1].data,
        [++self.counter, Math.random() * 10]
      ];
      self.chartOptions.series[2].data = [
        ...self.chartOptions.series[2].data,
        [++self.counter, Math.random() * 10]
      ];
    }, 1000);
  }
```

Live example: https://codesandbox.io/s/lyoymq1347

Kind regards!
