### ISSUE TITLE
How to use highcharts drilldown?

### ISSUE THREAD

**Issue by MrMaxorz** [highcharts/highcharts-vue#7]
I use drilldown(Highcharts) but it doesn't work.
Do you have any opinions?

**Comment by Denyllon** [comment]
hi @MrMaxorz,

Could you tell me what's happening exactly? I prepared an example with `drilldown` module included, and it seems everything works fine.
Are you sure, that you've imported the `drilldown` module in your application?
Here is the mentioned example: https://codesandbox.io/s/vj4kzwy40y

Best regards!

**Comment by MrMaxorz** [comment]
After I import highcharts and drilldown and use drilldown(highchart) same as your example. It's work Thank you.
