### ISSUE TITLE
How to call rangeSelector.buttons.events

### ISSUE THREAD

**Issue by valeriy-efimov** [highcharts/highcharts-vue#72]
rangeSelector: {

                        buttons: [{
                            text: '5min',
                            events: {
                                click: function () {
                                    ???
                                }
                            }
                        },
i need call my method if press button "5min"

**Comment by Denyllon** [comment]
hi @valeriy-efimov ,

Could you explain more precisely what you need, or what's the problem you had encountered?
Here is the example which shows how to call your own function when clicking range selector's button: https://codesandbox.io/s/zkw6vlx944

Kind regards!

**Comment by valeriy-efimov** [comment]
@Denyllon Ty but i need call my method in vue

https://codesandbox.io/s/y327y7ykzj

```
events: {
              click() {
                this.myMethod();
              }
            }
or
events: {
              click() {
                myMethod();
              }
            }
or
events: {
              click() {
                $root.myMethod();
              }
            }
```
not working

**Comment by Denyllon** [comment]
it's not working because `this` doesn't indicates on Vue instance within `click` function. It's completely normal behaviour of JavaScript. In order to call a function which is defined within your component, you can assign your Vue instance into variable, and then just call this variable within event function. That variable will be saved in function's closure. Please take a look at code and example below:

```js
export default {
  data() {
    const self = this
    return {
      chartOptions: {
        rangeSelector: {
          buttons: [{
            type: 'minute',
            count: 5,
            text: '5min',
            events: {
              click() {
                self.myMethod()
              }
            }
          }]
        },
        series: [{
          pointInterval: 60 * 1000,
          data: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3] 
        }]
      }
    };
  },
  methods: {
    myMethod() {
      alert('Button clicked!')
    }
  }
};
```

Live example: https://codesandbox.io/s/64ylvry1zw

**Comment by valeriy-efimov** [comment]
thanky very much =)
