### ISSUE TITLE
How do you add touch/mouse support for the 3d Scatter Chart

### ISSUE THREAD

**Issue by doitliketyler** [highcharts/highcharts-vue#74]
Hello. Wondering if anyone knew how exactly you would add mouse and touch events for rotation shown in this chart example:

https://www.highcharts.com/demo/3d-scatter-draggable

Thanks in advance.

**Comment by Denyllon** [comment]
Hello @doitliketyler ,

Thank you for contacting us.
There shouldn't be any problem with implementing that. Just need to move the code into separate file, wrap it with new function, where you will pass a specific chart instance. Please take a look at example below.

Live example: https://codesandbox.io/s/66olzvwpr

Kind regards!
