### ISSUE TITLE
Parameter 'createElement' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by breathcold** [highcharts/highcharts-vue#84]
![image](https://user-images.githubusercontent.com/24854685/58383611-735d4a00-800b-11e9-9b37-685a7a4725f1.png)
file----> highcharts-vue.d.ts
export class Chart extends _Vue {
    props: ChartPropsObject;
    template: string;
    watch: ChartWatchObject;
    beforeDestroy: () => void;
    mounted: () => void;
    render: (createElement) => VNode;
}

i changed it like this: 
export class Chart extends _Vue {
    props: ChartPropsObject;
    template: string;
    watch: ChartWatchObject;
    beforeDestroy: () => void;
    mounted: () => void;
    render: (createElement: Element) => VNode;
}

and then 
![image](https://user-images.githubusercontent.com/24854685/58383651-fb435400-800b-11e9-8c15-b53287666c3f.png)
works !
can update to fix this bug?

**Comment by Denyllon** [comment]
Hi @breathcold ,

It is already fixed in https://github.com/highcharts/highcharts-vue/pull/82, and will be published on npm this week.

Kind regards!
