### ISSUE TITLE
Highcharts has no default export

### ISSUE THREAD

**Issue by disovi** [highcharts/highcharts-vue#85]
Hi,
When using highcharts-vue in TypeScript project I receive error in highcharts-vue.d.ts
`error TS1192: Module '.../node_modules/highcharts/highcharts' has no default export.`

It can be fixed by replacing with `import * as Highcharts from 'highcharts'` and it seems right according to [Highcharts Typescript page](https://www.highcharts.com/docs/advanced-chart-features/typescript).

Error can also be fixed by **allowSyntheticDefaultImports** but we don't want to use this option in our project.

highcharts version: **7.1.1**
highcharts-vue version: **1.3.4**

**Comment by Denyllon** [comment]
Hello @disovi ,

Thank you for reporting the issue. Your solution looks correct, so it will be fixed in this way in upcoming version.

Kind regards!
