### ISSUE TITLE
networkgraph : Error #17

### ISSUE THREAD

**Issue by aroue2** [highcharts/highcharts-vue#87]
I'm using highcharts 7.1.2 and highcharts-vue 1.3.5, the latest versions, and it looks like networkgraph type of chart is just not supported. I'm trying to make a simple networkgraph and as soon as I add datas to my networkgraph it outputs the error 17.
Here are my chart options: 

        chartOptions: {
          chart: {
            type: 'networkgraph',
          },
          plotOptions: {
            networkgraph: {
              keys: ['from', 'to'],
            }
          },
          series: [{
            data: [1, 2],
          }]
        },

**Comment by KacperMadej** [comment]
Hi @aroue2 

Have you loaded and initialized the required module for networkgraph?
`highcharts/modules/networkgraph` is the path for `import`.
General info in docs apply: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

**Comment by aroue2** [comment]
Hello, thanks for you reply. Just before I read it, I realized networkgraph was a module I had to import, and your answer confirms it.

**Comment by JeongYunLee** [comment]
This is a pretty old issue, but I'm experiencing the exact same thing. Can you explain the  specific solution?
