### ISSUE TITLE
Cannot remove datas or nodes from networkgraph serie

### ISSUE THREAD

**Issue by aroue2** [highcharts/highcharts-vue#88]
Hello,

In a networkgraph with nodes and links, it looks like it's impossible to remove nodes, links or a serie without throwing an exception like "a.destroyElements is not a function" or "this.chart is undefined".
I made a https://jsfiddle.net/xL73gk4f/ showing the problem. Just open the browser console and click on clear. I tryed to remove the serie too, or links one by one but nothing works.

**Comment by pawelfus** [comment]
Simplified demo without vue: https://jsfiddle.net/BlackLabel/kxnqjuaz/

Reported in the core lib: https://github.com/highcharts/highcharts/issues/11176

Thanks for reporting this bug @aroue2 ! It's a regression, v7.1.1 works fine: https://jsfiddle.net/BlackLabel/2m5bzg3v/
