### ISSUE TITLE
updating scatter data doesn't work

### ISSUE THREAD

**Issue by Tzahile** [highcharts/highcharts-vue#91]
Hello,
I'm using scatter with dynamic data;
I render many points to form a circle, and with an interval I change their value to spin around the (0,0).
-- the points are in a format of `[ [x1, y1], [x2, y2], [x3, y3], ...]` as required for scatter.

I get the points as a prop and use watch to track any change.
In my watch I wrote:
```js
props: {
  spinData: Array,
},
watch: {
  spinData(newData){
    this.$children[0].chart.update(newData);
  }
}
```
I also tried like how you show in your demo - 
```js
this.$children[0].chart.series[0].data = newData;
```

For some reason, the graph doesn't change at all.. did I miss something?
in `Data()` I have
```js
updateArgs: [false, false, { duration: 3000 }]
```

Thanks in advance!

**Comment by Denyllon** [comment]
Hi @Tzahile ,

Thank you for reporting the issue.
Could you try to reproduce it on any sandbox platform (e.g Codesandbox or Stackblitz), and provide me with a link?

Kind regards!
