### ISSUE TITLE
viewFullscreen option in exporting, exiting full screen does not re-render graph

### ISSUE THREAD

**Issue by vetlevo** [highcharts/highcharts-vue#95]
The viewFullscreen option in exporting works well until you're closing the fullscreen, and the chart does not render to its original size.

Versions:
highcharts: 7.1.2,
highcharts-vue: 1.3.5,

Highcharts and the exporting module were imported directly in a Vue component. Tried to define it globally as well and encountered the same issue.

My chart is very basic, three data points. I have included the chart both as a top level element and within a more complex layout structure and encountered the same issue.

**Comment by Denyllon** [comment]
Hello @vetlevo ,

Thank you for reporting the issue.
I was trying to reproduce the issue described above, but unfortunately without any effect. Could you provide me with some live example where I would be able to see the problem? I've produced a test repository built from Vue CLI, and it looks that everything is working fine. If it is possible, please send me your email address so that I could attach the test project in the message.

Kine regards,
Daniel Studencki

**Comment by vetlevo** [comment]
Hello Daniel, 

Thank you for bringing this to your attention. I will look at producing a live example at the earliest convenience. 

My email address is vetle.volden-freberg@tellu.no

Cheers

Vetle Volden-Freberg

**Comment by Denyllon** [comment]
Thank you. I've sent the email with suggested working implementation.

**Comment by vetlevo** [comment]
Hello again Daniel,

I have taken a look at your example and it seems to work as intended. 

From what I can tell, the issue is reproducible by specifying relative sizes for height or width.

With a fixed initial size it seems to resize correctly after closing the fullscreen view. However, setting the sizes to a percentage relative to the parent container or auto seems to not work.

Regards,

Vetle Volden-Freberg

**Comment by Denyllon** [comment]
I'm still not able to reproduce the issue, even if the values are set in relative way. I've sent you another example with relative values, where you can see that everything is working properly.

**Comment by vetlevo** [comment]
You are indeed correct.

It would seem that my shameful incompentence in CSS was the issue ...

Thanks for looking into it for me, I'm sorry for wasting your time for this matter, however, the experience was invaluable to me.

Regards,

Vetle Volden-Freberg.

**Comment by curlka** [comment]
I've run into the same problem where the chart does not render to its original size after closing it in fullscreen.  What was the fix?

**Comment by Denyllon** [comment]
The problem was with a user's incorrect CSS implementation, so now it's hard to say what was wrong. @curlka Could you post here some information about how exactly did you resolve your issue?

**Comment by LakshmiVeejai** [comment]
Hi , I am also facing similar issue. Fullscreen option works, but on clicking ESC, chart is not resizing to grid. What am I missing . Could you please port here the correct way to handle this

**Comment by Denyllon** [comment]
@LakshmiVeejai Unfortunately there could be many cases where the problem can happen, but usually it's caused by third party libraries, or incorrect CSS implementation. I'm repeating the request to @curlka for solution. Could you share with other users the way of how did you resolve your issue?

**Comment by nicoleclearmetal** [comment]
I am having this issue as well. After viewing in the full screen the chart does not return to its original size. Any ideas?

**Comment by tskaiser** [comment]
The chart height fix didn't work for me, however listening for the fullscreen event and rerendering the graph using a key did.

So for the component

`<highcharts :key="rerenderKey"></highcharts>`

with

```
data: () => ({
    rerenderKey: true
}),
methods: {
    fullScreenChanged: function () {
        if (!document.fullscreenElement) {
            this.rerenderKey = !this.rerenderKey;
        }
    }
},
mounted: {
    this.$el.addEventListener('fullscreenchange', this.fullScreenChanged)
},
beforeDestroy: {
    this.$el.removeEventListener('fullscreenchange', this.fullScreenChanged)
}
```

In the parent component
