### ISSUE TITLE
3D Chart Options not working

### ISSUE THREAD

**Issue by Blackcell** [highcharts/highcharts-vue#97]
Hello,

I've successfully implemented highcharts-vue in the past. This is the first time trying to render a 3D chart. I am aware of the documentation:
https://api.highcharts.com/highcharts/chart.options3d

My options3d is set like:
```
options3d: {
   enabled: true,
   alpha: 15,
   beta: 15,
   depth: 50,
   viewDistance: 25
}
```

Am I missing an import as mentioned in the API docs? If so, how do we import the 3D module?

> Options to render charts in 3 dimensions. This feature requires highcharts-3d.js, found in the download package or online at code.highcharts.com/highcharts-3d.js.

**Comment by Denyllon** [comment]
Hello @Blackcell ,

Thank you for asking question.
You can import the `highcharts-3d` module as any other module from the package, what you can read in the [Importing Highcharts modules](https://github.com/highcharts/highcharts-vue#importing-highcharts-modules) section within wrapper documentation.
```js
import Highcharts from "highcharts";
import Highcharts3d from "highcharts/highcharts-3d";
import HighchartsVue from "highcharts-vue";

Highcharts3d(Highcharts);
Vue.use(HighchartsVue);
```

Here is the example of 3d chart using `highcharts-vue` wrapper: https://codesandbox.io/s/highcharts-vue-demo-rglkp

Kind regards!

**Comment by Blackcell** [comment]
@Denyllon Thanks buddy, that worked!

**Comment by DoracisMu** [comment]
@Denyllon it works  great!

**Comment by acgtwentyone** [comment]
How can i use Highcharts3d when  registering locally in my component ?

**Comment by acgtwentyone** [comment]
Thanks @Denyllon. You are right. I've solve this by registering it globally, importing the ```highcharts-3d``` module.
